### ISSUE TITLE
Having issue saving the topic model

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#270] opened 2021-10-07 13:39 UTC
from sklearn.feature_extraction.text import CountVectorizer
          
          vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words="english", min_df=2)
          
          from bertopic import BERTopic
          topic_model = BERTopic(embedding_model="roberta-base-nli-stsb-mean-tokens", n_gram_range= [1,3], vectorizer_model=vectorizer_model, calculate_probabilities=False, low_memory=True, verbose=True)
          topics, _ = topic_model.fit_transform(doc_list)

          Batches: 100%
          5082/5082 [3:56:53<00:00, 1.98it/s]
          2021-10-07 15:01:09,300 - BERTopic - Transformed documents to Embeddings
          2021-10-07 15:02:39,310 - BERTopic - Reduced dimensionality with UMAP
          2021-10-07 15:02:52,811 - BERTopic - Clustered UMAP embeddings with HDBSCAN        
  
          topic_model.save("./my_model", save_embedding_model="roberta-base-nli-stsb-mean-tokens")

When i try to save the model I get this error: 
            
            ---------------------------------------------------------------------------
            PanicException                            Traceback (most recent call last)
            <ipython-input-33-5c483e20bbf3> in <module>
            ----> 1 topic_model.save("./my_model", save_embedding_model="roberta-base-nli-stsb-mean-tokens")
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\bertopic\_bertopic.py in save(self, path, save_embedding_model)
               1204                 self.embedding_model = embedding_model
               1205             else:
            -> 1206                 joblib.dump(self, file)
               1207 
               1208     @classmethod
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in dump(value, filename, compress, protocol, cache_size)
                480             NumpyPickler(f, protocol=protocol).dump(value)
                481     else:
            --> 482         NumpyPickler(filename, protocol=protocol).dump(value)
                483 
                484     # If the target container is a file object, nothing is returned.
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in dump(self, obj)
                485         if self.proto >= 4:
                486             self.framer.start_framing()
            --> 487         self.save(obj)
                488         self.write(STOP)
                489         self.framer.end_framing()
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                715         if state is not None:
                716             if state_setter is None:
            --> 717                 save(state)
                718                 write(BUILD)
                719             else:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                558             f = self.dispatch.get(t)
                559             if f is not None:
            --> 560                 f(self, obj)  # Call unbound method with explicit self
                561                 return
                562 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_dict(self, obj)
                969 
                970         self.memoize(obj)
            --> 971         self._batch_setitems(obj.items())
                972 
                973     dispatch[dict] = save_dict
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                715         if state is not None:
                716             if state_setter is None:
            --> 717                 save(state)
                718                 write(BUILD)
                719             else:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                558             f = self.dispatch.get(t)
                559             if f is not None:
            --> 560                 f(self, obj)  # Call unbound method with explicit self
                561                 return
                562 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_dict(self, obj)
                969 
                970         self.memoize(obj)
            --> 971         self._batch_setitems(obj.items())
                972 
                973     dispatch[dict] = save_dict
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                715         if state is not None:
                716             if state_setter is None:
            --> 717                 save(state)
                718                 write(BUILD)
                719             else:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                558             f = self.dispatch.get(t)
                559             if f is not None:
            --> 560                 f(self, obj)  # Call unbound method with explicit self
                561                 return
                562 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_dict(self, obj)
                969 
                970         self.memoize(obj)
            --> 971         self._batch_setitems(obj.items())
                972 
                973     dispatch[dict] = save_dict
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                711 
                712         if dictitems is not None:
            --> 713             self._batch_setitems(dictitems)
                714 
                715         if state is not None:
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                715         if state is not None:
                716             if state_setter is None:
            --> 717                 save(state)
                718                 write(BUILD)
                719             else:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                558             f = self.dispatch.get(t)
                559             if f is not None:
            --> 560                 f(self, obj)  # Call unbound method with explicit self
                561                 return
                562 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_dict(self, obj)
                969 
                970         self.memoize(obj)
            --> 971         self._batch_setitems(obj.items())
                972 
                973     dispatch[dict] = save_dict
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                601 
                602         # Save the reduce() output and finally memoize the object
            --> 603         self.save_reduce(obj=obj, *rv)
                604 
                605     def persistent_id(self, obj):
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_reduce(self, func, args, state, listitems, dictitems, state_setter, obj)
                715         if state is not None:
                716             if state_setter is None:
            --> 717                 save(state)
                718                 write(BUILD)
                719             else:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                558             f = self.dispatch.get(t)
                559             if f is not None:
            --> 560                 f(self, obj)  # Call unbound method with explicit self
                561                 return
                562 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save_dict(self, obj)
                969 
                970         self.memoize(obj)
            --> 971         self._batch_setitems(obj.items())
                972 
                973     dispatch[dict] = save_dict
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in _batch_setitems(self, items)
                995                 for k, v in tmp:
                996                     save(k)
            --> 997                     save(v)
                998                 write(SETITEMS)
                999             elif n:
            
            ~\anaconda3\envs\tensorflow\lib\site-packages\joblib\numpy_pickle.py in save(self, obj)
                280             return
                281 
            --> 282         return Pickler.save(self, obj)
                283 
                284 
            
            ~\anaconda3\envs\tensorflow\lib\pickle.py in save(self, obj, save_persistent_id)
                576                 reduce = getattr(obj, "__reduce_ex__", None)
                577                 if reduce is not None:
            --> 578                     rv = reduce(self.proto)
                579                 else:
                580                     reduce = getattr(obj, "__reduce__", None)
            
            PanicException: no entry found for key

**Comment by randomrdrand** [comment] 2021-10-07 13:53
I should rerun the model?

**Comment by randomrdrand** [comment] 2021-10-07 14:18
Adding the path seems like resolving the problem: 


              Exception when trying to download http://sbert.net/models/sentence-transformers/all-distilroberta-v1.zip. Response 404
              SentenceTransformer-Model http://sbert.net/models/sentence-transformers/all-distilroberta-v1.zip not found. Try to create it from scratch
              Try to create Transformer Model sentence-transformers/all-distilroberta-v1 with mean pooling
              Downloading: 100%
              653/653 [00:00<00:00, 8.73kB/s]
              Downloading: 100%
              329M/329M [00:28<00:00, 11.5MB/s]
              Downloading: 100%
              798k/798k [00:00<00:00, 877kB/s]
              Downloading: 100%
              456k/456k [00:00<00:00, 876kB/s]
              Downloading: 100%
              1.36M/1.36M [00:00<00:00, 1.65MB/s]
              Downloading: 100%
              239/239 [00:00<00:00, 6.85kB/s]
              Downloading: 100%
              333/333 [00:00<00:00, 9.82kB/s]
              Batches: 0%
              11/5082 [01:47<14:11:07, 10.07s/it]

**Comment by randomrdrand** [comment] 2021-10-07 15:30
I have the following:

bertopic==0.8.1
sentence-transformers==2.1.0
 
When i try: 

     !pip install --upgrade bertopic 

I discovered that I have 2.5 tensorflow version and bertopic could upgrade how to resolve?

Ps. I am not running on colab anymore

**Comment by MaartenGr** [comment] 2021-11-04 06:44
Since the issue has been without activity for some time, I am closing this for now. However, if you are running into this issue still or want to discuss it further, please let me know! I'll reopen it and see if we can fix the issue.

**Closed by MaartenGr** 2021-11-04 06:44 UTC

**Comment by MaartenGr** [comment] 2024-03-21 12:34
@tmsss Please share your **full** code along with the **full** error message. Without it, it is difficult to say what exactly is going on.

**Comment by tmsss** [comment] 2024-03-21 15:44
Thanks for the reply @MaartenGr, while organizing the code to post here I've found were the problem was. I don't know if I've missed this information in the documentation, but it looks like that the save_ctfidf=True parameter doesn't work with the OnlineCountVectorizer. I've changed to CountVectorizer and it works now.

**Comment by RomanBlaaas** [comment] 2024-11-28 12:00
When I try to save my model with save_ctfidf=True I got the following error message:   File "C:\Users\wkblar386\PycharmProjects\TextUnderstanding\main.py", line 71, in <module>
    main_train_model(corpus)
  File "C:\Users\wkblar386\PycharmProjects\TextUnderstanding\topicModel\train_model.py", line 153, in main_train_model
    pre_trained_model.save(path,
  File "C:\Users\wkblar386\PycharmProjects\TextUnderstanding\.venv\lib\site-packages\bertopic\_bertopic.py", line 3355, in save
    save_utils.save_ctfidf_config(model=self, path=save_directory / "ctfidf_config.json")
  File "C:\Users\wkblar386\PycharmProjects\TextUnderstanding\.venv\lib\site-packages\bertopic\_save_utils.py", line 372, in save_ctfidf_config
    json.dump(config, f, indent=2)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable

**Comment by RomanBlaaas** [comment] 2024-11-28 12:00
here is my full Code:


import os

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired

from sklearn.feature_extraction.text import TfidfVectorizer
from hdbscan import HDBSCAN
from umap import UMAP
from sentence_transformers import SentenceTransformer

random_state = 42


def train_topic_model(features):

    min_cluster_size = int(input("Please enter your chosen value for min_cluster_size. "
                                 "This is the minimum size of a cluster which get created: "))
    print()

    min_sample_size = int(input("Please enter your chosen value for min_sample_size. "
                                  "Setting this value significantly lower than min_cluster_size might help you to "
                                  "reduce the amount of noise you will get: "))
    print()

    n_components = int(input("Please enter your chosen value for dimension reduction: "))
    print()

    top_words = int(input("Please enter your chosen value for top words extraction: "))
    print()

    # paraphrase-multilingual-mpnet-base-v2/ paraphrase-multilingual-MiniLM-L12-v2/ all-distilroberta-v1
    embedding_model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
    embeddings = embedding_model.encode(features, show_progress_bar=True)

    umap_model = UMAP(
        n_neighbors=10,
        n_components=n_components,
        min_dist=0.01, metric='cosine',
        random_state=random_state,
        low_memory=True
    )

    hdbscan_model = HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_sample_size,
        metric='euclidean',
        cluster_selection_method='eom',
        prediction_data=True,
        gen_min_span_tree=True
    )

    custom_stopwords = ['hallo', 'person', 'gruß', 'danke', 'bitte', 'ticket', 'grüßen', 'http']

    vectorizer_model = TfidfVectorizer(
        stop_words=custom_stopwords,
        max_df=float(0.8),
        min_df=int(2),
        max_features=int(5000),
        use_idf=True,
        smooth_idf=True,
        norm='l2',
        ngram_range=(1, 1))

    keybert_model = KeyBERTInspired()
    representation_model = {"KeyBERT": keybert_model}

    topic_model = BERTopic(
        language="de",
        verbose=True,
        top_n_words=top_words,
        embedding_model=embedding_model,
        n_gram_range=(1, 1),
        hdbscan_model=hdbscan_model,
        umap_model=umap_model,
        calculate_probabilities=True,
        representation_model=representation_model,
        vectorizer_model=vectorizer_model,
    )

    topics, _ = topic_model.fit_transform(features,embeddings)

    topic_info = topic_model.get_topic_info()
    topic_numb = len(topic_info)

    print()
    print(f'BERTopic model Info: {topic_info}')
    print(f'Found topics: {topic_numb}')
    print()

    keybert_topic_labels = {topic: " ".join(list(zip(*values))[0][:1]) for topic, values in
                            topic_model.topic_aspects_["KeyBERT"].items()}

    topic_model.set_topic_labels(keybert_topic_labels)

    # Visualization of the Intertopic Distance Map
    fig_idm = topic_model.visualize_topics(custom_labels=True)
    print("Plot Inter Topic Distance Map")
    print("****************************")
    fig_idm.show()

    # Visualization of the barchart plot
    fig_barchart = topic_model.visualize_barchart(top_n_topics=topic_numb, n_words=10, custom_labels=True)
    print("Plot Barchart")
    print("****************************")

    fig_barchart.show()

    # Get reduced embeddings
    reduced_embeddings = UMAP(n_neighbors=15, n_components=2, min_dist=0.0, metric='cosine').fit_transform(embeddings)

    # Visualization of the documents and topic clustering
    fig_cluster = topic_model.visualize_documents(features,
                                                  reduced_embeddings=reduced_embeddings,
                                                  hide_annotations=True,
                                                  custom_labels=True)
    print("Plot Topic Cluster")
    print("****************************")
    fig_cluster.show()

    return topic_model


def main_train_model(dataframe):

    features = list(dataframe['DOC_TEXT_CLEANED_PP'])

    pre_trained_model = train_topic_model(features)

    while True:

        print()
        print("Please choose one of the following options:")
        print("Input 'y' : for saving the trained model and exit to the main menu")
        print("Input 'n' : for exit to the main menu without saving of the model")
        print()

        user_choice = input("Please enter your chosen option: ")

        if user_choice.lower() == "y":

            print()
            user_model_name = input("Please enter your chosen model name: ")

            path = os.path.join("C:\\Users\\wkblar386\\PycharmProjects\\TextUnderstanding\\topicModel\\Model",
                                f"TopicModel_{user_model_name.strip()}")

            pre_trained_model.save(path,
                                   serialization="pytorch",
                                   save_ctfidf=False,
                                   save_embedding_model=True)

            print("Topic model get saved. Please restart the program!")
            print()
            break

        elif user_choice.lower() == "n":
            print("Exit without saving ... ")
            break

        else:
            print("Invalid option. Please try again.")

**Comment by RomanBlaaas** [comment] 2024-11-28 12:01
I use the latest Version from BERTopic : (.venv) PS C:\Users\wkblar386\PycharmProjects\TextUnderstanding> pip show bertopic
Name: bertopic
Version: 0.16.4
 How can I fix this issue?

**Comment by MaartenGr** [comment] 2024-11-29 06:37
@RomanBlaaas Is this is a duplicate of #2230?

**Comment by RomanBlaaas** [comment] 2024-11-29 06:41
Yes, I was not sure about the right forum/ chapter.
