### ISSUE TITLE
reduce_topics() - ValueError: max_df corresponds to < documents than min_df

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [MaartenGr/BERTopic#810] opened 2022-10-28 18:59 UTC
Using `topic_model.reduce_topics(docs, nr_topics="auto")`, 
I get an error `ValueError: max_df corresponds to < documents than min_df`. 
This does not happen if I explcitly enter nr_topics as a number.
The original number of topics was 350 (including the -1 topic)
The version is 0.12

Original model settings:
```
vectorizer_model = CountVectorizer(stop_words="english", ngram_range=(1, 2), 
                                   token_pattern=u'(?ui)\\b\\w*[A-Za-z]{2,}\\w*\\b',
                                   min_df=100)

sentence_model = SentenceTransformer("all-mpnet-base-v2", device="cuda")

topic_model = BERTopic(embedding_model=sentence_model,
                       vectorizer_model=vectorizer_model,
                       calculate_probabilities=False, 
                       verbose=True, 
                       min_topic_size=300,
                       nr_topics = "auto")
```
Trace below:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <timed exec>:1, in <module>

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/bertopic/_bertopic.py:1499, in BERTopic.reduce_topics(self, docs, nr_topics)
   1496 documents = pd.DataFrame({"Document": docs, "Topic": self.topics_})
   1498 # Reduce number of topics
-> 1499 documents = self._reduce_topics(documents)
   1500 self._merged_topics = None
   1501 self._map_representative_docs()

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/bertopic/_bertopic.py:2630, in BERTopic._reduce_topics(self, documents)
   2628         documents = self._reduce_to_n_topics(documents)
   2629 elif isinstance(self.nr_topics, str):
-> 2630     documents = self._auto_reduce_topics(documents)
   2631 else:
   2632     raise ValueError("nr_topics needs to be an int or 'auto'! ")

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/bertopic/_bertopic.py:2712, in BERTopic._auto_reduce_topics(self, documents)
   2710 self.topic_mapper_.add_mappings(mapped_topics)
   2711 documents = self._sort_mappings_by_frequency(documents)
-> 2712 self._extract_topics(documents)
   2713 self._update_topic_size(documents)
   2714 return documents

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/bertopic/_bertopic.py:2389, in BERTopic._extract_topics(self, documents)
   2380 """ Extract topics from the clusters using a class-based TF-IDF
   2381 
   2382 Arguments:
   (...)
   2386     c_tf_idf: The resulting matrix giving a value (importance score) for each word per topic
   2387 """
   2388 documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
-> 2389 self.c_tf_idf_, words = self._c_tf_idf(documents_per_topic)
   2390 self.topic_representations_ = self._extract_words_per_topic(words)
   2391 self._create_topic_vectors()

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/bertopic/_bertopic.py:2519, in BERTopic._c_tf_idf(self, documents_per_topic, fit, partial_fit)
   2517     X = self.vectorizer_model.partial_fit(documents).update_bow(documents)
   2518 elif fit:
-> 2519     self.vectorizer_model.fit(documents)
   2520     X = self.vectorizer_model.transform(documents)
   2521 else:

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:1169, in CountVectorizer.fit(self, raw_documents, y)
   1157 """Learn a vocabulary dictionary of all tokens in the raw documents.
   1158 
   1159 Parameters
   (...)
   1166 self
   1167 """
   1168 self._warn_for_unused_params()
-> 1169 self.fit_transform(raw_documents)
   1170 return self

File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:1217, in CountVectorizer.fit_transform(self, raw_documents, y)
   1213 min_doc_count = (min_df
   1214                  if isinstance(min_df, numbers.Integral)
   1215                  else min_df * n_doc)
   1216 if max_doc_count < min_doc_count:
-> 1217     raise ValueError(
   1218         "max_df corresponds to < documents than min_df")
   1219 if max_features is not None:
   1220     X = self._sort_features(X, vocabulary)

ValueError: max_df corresponds to < documents than min_df
```

**Comment by MaartenGr** [comment] 2022-10-29 05:36
This is an error that might happen with certain values of `min_df` when using the CountVectorizer. However, I would have expected it to already give this error message when you initially trained the model, not necessarily when you reduced the number of topics. It seems then, that it is given an input that somehow does not have the right properties for this to work, which is surprising since topics are concatenated which should provide even more data. This is a bit of a longshot but is your data publicly available? It would help me go a bit more in-depth into what is happening here. 

Other than that, could you train your model with specifying `BERTopic(nr_topics="auto")` instead of using `reduce_topics`? Also, it may be worthwhile to use a float for `min_df` to remove a percentage rather than a fixed amount. It is definitely not ideal but perhaps it helps.

**Comment by ChrisPalmerNZ** [comment] 2022-10-29 08:01
Thanks Maarten

The data is not publicly available, it is over 3 million tweets I have
recently gathered but is not yet in a form suitable for publication -
though I can give you the tweet ids if you think it will help...

I tried with nr_topics="auto" initially, but aborted it as it was taking a
long time to run, so I thought I would save time by using reduce_topics -
even with that setting it took just over a day to train. Do you think auto
will be much slower - I am happy to retry a bit later on when I have spare
capacity!

I will try a float into min_df - though I didn't understand your comment
about a percentage - does it automatically assume a percentage if a float
is passed?

Kind Regards
Chris

**Comment by drob-xx** [comment] 2022-10-29 15:47
@ChrisPalmerNZ from the [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) doco - 

> max_df float in range [0.0, 1.0] or int, default=1.0
> When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.
> 
> min_dff loat in range [0.0, 1.0] or int, default=1
> When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

So you can specify these values as integers or floats. If integers they are absolute numbers of documents, if floats they are percentages of the total number of documents passed. 

min_df must be less than max_df and it looks like the error is triggered because this is not true. The difficult thing with your problem is that it is not clear how you were able to get the model to fit in the first place without throwing this error before you called reduce_topics. My first thought was that the docs changed between calls. Could you provide the code that first runs fit_transform and then runs reduce_topics including the passing of the docs?

I would also point you to [TopicTuner](https://github.com/drob-xx/TopicTuner) which I'm working on as an alternative method to control the number of topics (without the sacrifice of large numbers of -1 documents).

**Comment by MaartenGr** [comment] 2022-10-29 18:12
> The data is not publicly available, it is over 3 million tweets I have
recently gathered but is not yet in a form suitable for publication -
though I can give you the tweet ids if you think it will help...

No problem, it was just a long shot to see if we can replicate the issue. 

> I tried with nr_topics="auto" initially, but aborted it as it was taking a
long time to run, so I thought I would save time by using reduce_topics -
even with that setting it took just over a day to train. Do you think auto
will be much slower - I am happy to retry a bit later on when I have spare
capacity!

Generally, `nr_topics="auto"` when instantiating BERTopic or when using `reduce_topics` should not make that big of a difference. However, there might be small changes between them and by also seeing if the issue persists when instantiating BERTopic that way helps in understanding what exactly the issue is here. It is not ideal but you could also use an integer instead for `nr_topics` after having trained the model and explored the data. `"auto"` is mostly there for a quick clustering of the generated topics. When you have explored the topics, you can quickly get a sense of how many there should roughly be in the data. So using an integer value to specify the number of topics that you want might also work in your case.

**Comment by ChrisPalmerNZ** [comment] 2022-10-29 22:58
Hello Maarten

To answer a previous observation, I have not altered the documents at all. 

I am now finding the same problem with calling `reduce_topics` with a specific number of topics! 

My approach with trying to reduce topics is to re-load the original model each time, then call `reduce_topics`. I have successfully done this for 200, 150, and 100 topics on the current model, but when trying to do it for 75 topics the same error came up again. 

Would it be useful for you if I could privately share a .pkl or .csv of the docs and the model with you? I am also happy to retrain the model with "auto" but it will be a few days before I can do so, as I have to use my compute resources to meet a deadline...

Here is my code for `fit_transform` and then `reduce_topics`, dftxt is a pandas dataframe and is consistent:
```
docs = dftxt.topictext.to_list()
topics, probs = topic_model.fit_transform(docs)

# save topic model
master_model = str(MODEL_PATH/"0_master_nostop_n2.model")
topic_model.save(master_model)

# reload topic model - for reduce to 200 
topic_model_200 = topic_model.load(master_model)
topics = topic_model.topics_
probs  = topic_model.probabilities_

# reduce topics
topic_model_200.reduce_topics(docs, nr_topics=200);
```

**Comment by MaartenGr** [comment] 2022-10-30 05:28
Alright, it turned out to be a bit more straightforward than I had anticipated... Let's take a look at the last part of the error message:

```
File ~/anaconda3/envs/deep-learning/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:1217, in CountVectorizer.fit_transform(self, raw_documents, y)
   1213 min_doc_count = (min_df
   1214                  if isinstance(min_df, numbers.Integral)
   1215                  else min_df * n_doc)
   1216 if max_doc_count < min_doc_count:
-> 1217     raise ValueError(
   1218         "max_df corresponds to < documents than min_df")
   1219 if max_features is not None:
   1220     X = self._sort_features(X, vocabulary)

ValueError: max_df corresponds to < documents than min_df
```

What stands out in this error message is that the error is given as a result of the variables `max_doc_count` and `min_doc_count`, which seem to relate directly to `max_df` and `min_df`. They even have the same property `x > y` but have different variable names. The names of the variables indicate that we should look at the total number of documents and to a lesser extent the number of words. In other words, it counts whether a word appears in a document and now how often. As a result, when you specify `min_df=100` the documents over which you are then using the `CountVectorizer` need to have at least 100 documents. Since documents are concatenated in BERTopic, if you specify `min_df=100`, you will need at least 100 topics. Hence why you code is running for `nr_topics=100` but not `nr_topics=75`. 

In practice, we can test this with:

```python
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

# This works
vectorizer = CountVectorizer(min_df=4).fit(corpus)

# This does not because we only have 4 documents
vectorizer = CountVectorizer(min_df=5).fit(corpus)
```

I believe this should be the solution for you, simply lowering the `min_df` to something like 50 is likely to already prevent the error from happening when you use `nr_topics="auto"`. If I am correct, then thank you for trying some stuff out on your end, it definitely helped in finding this out.

**Comment by ChrisPalmerNZ** [comment] 2022-10-30 09:58
Thanks Maarten

I think I understand, that it is impossible to reduce to 75 topics because my `min_df=100` has already specified that I need at least 100 topics in my model - is that correct?

But, why do you think the request to use `nr_topics = "auto"` in `reduce_topics` fell over - last time I used that after fitting a model that had `nr_topics = "auto"` I did not use a `min_df` setting. The reduced topics were only somewhat reduced, certainly not in the order of what we would see here, where the original topic count was 350 and the minimum specified as 100, for `auto` to go below 100. Anyway, shouldn't the `auto` setting have at least accounted for the specified minimum and prevented itself from trying to go lower than that?

At this stage, would you just like me to retry fitting the model with min_df=50, and see then if I can reduce topics to 75? Or, for that matter, to 50, but not to (say) 25? Or, is it so self-evident that it is not needed?

**Comment by MaartenGr** [comment] 2022-10-30 11:48
> I think I understand, that it is impossible to reduce to 75 topics because my min_df=100 has already specified that I need at least 100 topics in my model - is that correct?

Yes, that is in essence what I think is happening here. 

> But, why do you think the request to use nr_topics = "auto" in reduce_topics fell over - last time I used that after fitting a model that had nr_topics = "auto" I did not use a min_df setting. The reduced topics were only somewhat reduced, certainly not in the order of what we would see here, where the original topic count was 350 and the minimum specified as 100, for auto to go below 100. 

It highly depends on the data that you have and the resulting topics that are being created. So it is difficult to say why it differs between use cases. However, it may just be that the topics that you have in this model are very similar to one another or that you have a large number of microclusters that all can be merged into a single one. 

> Anyway, shouldn't the auto setting have at least accounted for the specified minimum and prevented itself from trying to go lower than that?

Unfortunately, it is not that straightforward. The auto setting is using HDBSCAN to cluster the topics and will automatically detect the number of clusters. There is no way of telling the model directly that it can only find a minimum number of topics. There are a few tricks that we can do here to solve that issue but they are quite hacky (e.g., updating the `min_df` parameter based on the number of clusters found). 

> At this stage, would you just like me to retry fitting the model with min_df=50, and see then if I can reduce topics to 75? Or, for that matter, to 50, but not to (say) 25? Or, is it so self-evident that it is not needed?

I am a big fan of testing things out, so it would be great if you can try it with `min_df=50` and then use `nr_topics=75` to see if that works. If so, then I am quite sure that it was the `min_df` where things went haywire.

**Comment by ChrisPalmerNZ** [comment] 2022-10-30 11:50
OK, thanks Maarten. It will likely be a few days before I can get back to you - I really appreciate the attention you are giving to this...

**Comment by davidlenz** [comment] 2022-11-21 16:19
I've encountered the same issue as reported by @ChrisPalmerNZ and i think the conclusions drawn by @MaartenGr are a) on point and b) in line with what i observed fiddling with the parameters. However, i think there is some additional effect at play here relating to the total number of documents provided that can also lead to 'ValueError: max_df corresponds to < documents than min_df`.

I'll go over four observations for illustration.

Tests
-----------------------------------

1. First the following reproducible example throws the error, imo because `min_df` and `nr_topics` interfere as outlined above by @MaartenGr .

```python
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic


nr_topics = 50
min_df = 50
max_df = 0.65
# make sure that min_df is smaller than or equal to `nr_topics * max_df`
# Note: experiments showed that min_df_adj + 2 still worked, so not sure about
# the relationship expressed in below formula
min_df_adj = min(min_df, int(np.floor(nr_topics*max_df)))
print(min_df, min_df_adj)

# make docs
newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
news = pd.DataFrame([newsgroups_train.data, newsgroups_train.target.tolist()]).T
news.columns = ['text', 'target']
docs = news.text.values.tolist()

# define vectorizer
vectorizer_model = CountVectorizer(ngram_range=(1, 3), analyzer="word", max_df = max_df, min_df= min_df)
#vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words=stopword_list, analyzer="word", max_df = max_df, min_df= min_df)

# define bertopic
topic_model = BERTopic(language="multilingual", 
                       calculate_probabilities=False, 
                       vectorizer_model=vectorizer_model,
                       verbose=True,
                       min_topic_size = 10,
                       #nr_topics=nr_topics
                       )

# fit
topics, probs = topic_model.fit_transform(docs[:5000])
# ValueError: max_df corresponds to < documents than min_df
```

2. Lowering `min_df` to `min_df_adj` resolves the error:

```python
[...]
# define vectorizer
vectorizer_model = CountVectorizer(ngram_range=(1, 3), analyzer="word", max_df = max_df, min_df= min_df_adj)
#vectorizer_model = CountVectorizer(ngram_range=(1, 3), stop_words=stopword_list, analyzer="word", max_df = max_df, min_df= min_df)

# define bertopic
topic_model = BERTopic(language="multilingual", 
                       calculate_probabilities=False, 
                       vectorizer_model=vectorizer_model,
                       verbose=True,
                       min_topic_size = 10,
                       #nr_topics=nr_topics
                       )

# fit
topics, probs = topic_model.fit_transform(docs[:5000])
# no error
```


3. However using fewer docs (5k->1k) produces the error again:

```python
[...]
# fit
topics, probs = topic_model.fit_transform(docs[:1000])
#ValueError: max_df corresponds to < documents than min_df
```

4. Ok, maybe 1k docs is a bit few to ask for 50 topics, Trying to find threshold for # docs for choosen settings. Seems like ~4.5k docs is the minimum to not get the error given the other parameters.
```python
[...]
# fit
topics, probs = topic_model.fit_transform(docs[:4000]) # 2500, 3000, 3500
#ValueError: max_df corresponds to < documents than min_df
topics, probs = topic_model.fit_transform(docs[:4500])
# no error
```

-----------------------------

My take from that is that to not get the error you need to have a) enough documents to provide content for the amount of topics you asked for and b) have a `min_df` that corresponds to `max_df`  with respect to `nr_topics`

From this it follows if you get the error try to a) reduce `nr_topics`  if your doc count is low or b) adjust `min_df` and `max_df` with regard to eachother and also 'nr_topics' so they don't produce impossible tradeoffs for the vectorizer.

**Closed as completed** 2023-05-23 09:18 UTC
