### ISSUE TITLE
get_topic() and get_topics() "top n words" parameter

### ISSUE THREAD

**Issue by meaneych** [MaartenGr/BERTopic#499] opened 2022-04-09 13:26 UTC
Hi Maarten. Thanks for creating the BERTopic package. I've been playing around with it on medical texts. It works great!!

Simple question: running help(topic_model.get_topic) says the function takes single integer argument (the topic ID); and returns the "top-n" words for a specific topic and their c-TF-IDF scores. 

How do I control the number of returned words/scores? Currently top-n seems to be top-10? What if I want top-20? Or even all scores associated with a given topic? Similar to the right hand phi matrix in LDA/NMF models (i.e. matrix of per-topic distribution over words)?

Thanks for clarifying.
Chris

**Comment by MaartenGr** [comment] 2022-04-10 06:10
Glad to hear that the model is working well for you! If there are things that you would like to see improved or output that you are not satisfied with, let me know. Any feedback is highly appreciated. 

> How do I control the number of returned words/scores? Currently top-n seems to be top-10? What if I want top-20?

You can control the top_n words in a topic with the `top_n_words` variable when instantiating BERTopic. In other words, run the following:

```python
topic_model = BERTopic(top_n_words=30)
```

> Or even all scores associated with a given topic? Similar to the right hand phi matrix in LDA/NMF models (i.e. matrix of per-topic distribution over words)?

In BERTopic, that is the c-TF-IDF matrix that is generated after training the model. You can access that as follows:

```python
topic_model.c_tf_idf
```

**Comment by meaneych** [comment] 2022-04-10 12:11
Thanks Maarten, super helpful reply.

I think it is topic_model.c_tf_idf that I need which returns a scipy.sparse.csr.csr_matrix.

The row dimension of the matrix is (K+1) topics; where K is the number of topics I specify; and +1 captures the "noise" topic added by BERTopic. Are the indices of this in one-to-one correspondence with the topics. i.e. index=0 is topic=-1; index=1 is topic=0; index=K is topic=(K-1); etc. in the BERTopic outputs?

And similarly, if there are 0...(V-1) column indices of the sparse matrix; how to I grab the equivalent length string vector of words/tokens to map these to columns labels.

I like pandas - so what I want to do is something like below (where words is a list containing words in my vocabularly; which are in correspondence with columns of the sparse matrix: 

'''
phi = pd.DataFrame.sparse.from_spmatrix(topic_model.c_tf_idf)
phi.columns = words
''''

Thanks again for your help!! And great work on BERTopic (love it)!!

**Comment by MaartenGr** [comment] 2022-04-11 13:15
> The row dimension of the matrix is (K+1) topics; where K is the number of topics I specify; and +1 captures the "noise" topic added by BERTopic. Are the indices of this in one-to-one correspondence with the topics. i.e. index=0 is topic=-1; index=1 is topic=0; index=K is topic=(K-1); etc. in the BERTopic outputs?

From the top of my head, it is indeed that index 0 corresponds to topic -1, 1 to 0, etc. You can check it by accessing the highest values of each topic and see if they correspond to what you find when you run `topic_model.get_topic(0)`. 

> And similarly, if there are 0...(V-1) column indices of the sparse matrix; how to I grab the equivalent length string vector of words/tokens to map these to columns labels.

This columns correspond to the feature names that you can find in `topic_model.vectorizer_model.get_feature_names()` since the sparse matrix is generated through the `CountVectorizer`. 

Hopefully, this helps a bit!

**Comment by MaartenGr** [comment] 2022-07-13 08:15
Seeing as this was active a while ago, I am closing this for now. If you run into any issues, please let me know and I'll make sure to re-open it!

**Closed by MaartenGr** 2022-07-13 08:15 UTC

**Comment by satrio-yudhoatmojo** [comment] 2022-12-11 20:04
Hi, I'm interested in exploring the `topic_model.c_tf_idf_` attribute.  This is a snippet of the values:

`(52, 10436)   0.03358649867578632
  (52, 2619)    0.024528757379686454
  (52, 2616)    0.01884963599166409
  (52, 1615)    0.004476882869413102`

I'm assuming 52 is the topic number and the numbers next to it are the indexes to the word. Am I correct? If yes, how do I know which words are indexed to these numbers?

**Comment by MaartenGr** [comment] 2022-12-15 07:56
@satrio-yudhoatmojo You can find the corresponding indices and words by accessing the CountVectorizer with 

```python
words = topic_model.vectorizer_model.get_feature_names_out()
```

or  

```python
words = topic_model.vectorizer_model.get_feature_names()
```

The resulting words are ordered and should match the indices.

**Comment by leoalz** [comment] 2023-05-27 18:30
Hello,

First I'd like to thank you for your efforts, it is truly a great tool!

I trained the model using top_n_words = 30, but when I want to get topics words, I only have the first 10... Do you have any idea why is that, and how can I have access to the 30 words?

Here are the parameters used for training:
top_n_words = 30
n_topics = None
min_topic_size = 20
embedding_model = 'paraphrase-multilingual-mpnet-base-v2'
vectorizer_model = None
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True) 
representation_model = MaximalMarginalRelevance(diversity=0.7) 

Thank you in advance.

**Comment by MaartenGr** [comment] 2023-05-28 04:55
@leoalz When you use MMR, you give it a certain number of keywords, for example 30. It then reduces those keywords to a smaller size to find the ones that are diverse enough, for example 10. In other words, even though you set `top_n_words` to 30, in MaximalMarginalRelevance, this value is set at 10. So you will have to update it there but also keep in mind that you set the initial `top_n_words` higher than those in MMR.

**Comment by leoalz** [comment] 2023-05-28 05:01
Thank you for your response.

If I understand well, I should set the parameter top_n of MaximalMarginakRelevance to the actual number of keywords wanted?

According to you and your experience, if I want let’s say 20 or 30 keywords in the end, with a maximal marginal relevance diversity of 0.7, what should be the top_n_words for training of BERTopic model? 40 or 50?

**Comment by MaartenGr** [comment] 2023-05-28 05:04
> If I understand well, I should set the parameter top_n of MaximalMarginalRelevance to the actual number of keywords wanted?

That is correct!

> According to you and your experience, if I want let’s say 20 or 30 keywords in the end, with a maximal marginal relevance diversity of 0.7, what should be the top_n_words for training of BERTopic model? 40 or 50?

There is some manual tuning there involved but I would indeed roughly double the number of initial keywords such that MMR has a sufficient number of keywords for it to diversify.

**Comment by leoalz** [comment] 2023-05-28 05:06
Thank you I appreciate your help :)
And we’ll done again with the model, it is incredibly useful and practical for multilingual NLP.

**Comment by leoalz** [comment] 2023-05-28 19:59
Hello again,

Having different values of top_n-words for BERTopic and MMR raise the error 
`ValueError: Length of weights not compatible with specified axis.`

To avoid that, those issues #1054 and #1259 seems to say that it is necessary to set them to the same value, which contradict what you were saying...

Could you explain a bit more what is the correct way to set top_n_words please?

**Comment by MaartenGr** [comment] 2023-05-29 17:15
@leoalz Could you share which version of BERTopic you are using and could you share the entire error log? In principle, it should be as I explained above. What you encounter might be an old issue.

**Comment by leoalz** [comment] 2023-05-29 20:48
Hello,

When setting the same value for both, it's working fine.

I cannot reproduce right now as it takes more than an hour of running before raising the error, but I'll try to provide with more detailed information in the week!

**Comment by leoalz** [comment] 2023-05-31 22:12
Hello,

So I'm using bertopic library version 0.14.1

Here is the preprocessing I apply on my dataset (texts are stored by language segment in dict, e.g. {'fr':'je suis présent', 'en':'I am here',...}:

`arabic_punctuation = '''÷×؛<>_()*&^%][ـ،/:"؟.,'{}~¦+|!”…“–ـ'''
combined_punctuation = ''.join(set(string.punctuation + hanzi.punctuation + pinyin.punctuation + arabic_punctuation))
escaped_punctuation = re.escape(combined_punctuation) # to handle regex special characters (e.g. [])
for i, row in text_df.iterrows():
        lang_codes = list(row['text_segments'].keys())
        for lc in lang_codes:
            if lc in lang_codes_supported_multiling_bert: 
                text_to_concat = str(row['text_segments'][lc])
                if text_to_concat: 
                    if text_to_concat.lower() != 'nan':
                        # lower text, remove emojis, new lines and punctuation from text
                        text_to_concat = re.sub('\n', ' ', emoji_removal(text_to_concat.lower()))
                        text_to_concat = re.sub(f'[{escaped_punctuation}]', ' ', text_to_concat)
                        text_to_concat = remove_unicode_symbols(text_to_concat, unicode_symbol_ranges)
                        extracted_langdetect_df.at[i, 'text_for_BERTopic'] += str(text_to_concat) + ' '
    # remove trailing whitespace, and sequences of multiple consecutive whitespaces
    text_df['text_for_BERTopic'] = text_df['text_for_BERTopic'].str.strip()
    text_df['text_for_BERTopic'] = text_df['text_for_BERTopic'].str.replace('\s+', ' ', regex=True)`

Here are the parameter of the model:
`
top_n_words = 30  # for Bertopic
n_topics = None
min_topic_size = 20
embedding_model = 'paraphrase-multilingual-mpnet-base-v2' # >1h to train
vectorizer_model = None
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True) 
representation_model = MaximalMarginalRelevance(diversity=0.7, top_n_words=10) # different top_n_words
`

And of course I train the model with a list of clean documents:
`
text_list = df['text_for_BERTopic'].to_list()
topics, probs = topic_model.fit_transform(text_list)`

And here is the error raised:
`
Traceback (most recent call last):
  File "/home/user/project/test_bert_topn_error.py", line 87, in <module>
    model_save_path = topic_keyword.train_BERTopic_model(TOPIC_DATA_BERT_PATH, f"{list_name}_multilingual", list_extracted_for_BERT_df, top_n_words=top_n_words, n_topics=n_topics, min_topic_size=min_topic_size, embedding_model=embedding_model, vectorizer_model=vectorizer_model, ctfidf_model=ctfidf_model, representation_model=representation_model)
  File "/home/user/project/topic_keyword/topic_keyword_BERTopic.py", line 96, in train_BERTopic_model
    topics, probs = topic_model.fit_transform(extracted_text_list)
  File "/home/user/venv/lib/python3.9/site-packages/bertopic/_bertopic.py", line 366, in fit_transform
    self._extract_topics(documents)
  File "/home/user/venv/lib/python3.9/site-packages/bertopic/_bertopic.py", line 2982, in _extract_topics
    self._create_topic_vectors()
  File "/home/venv/lib/python3.9/site-packages/bertopic/_bertopic.py", line 3094, in _create_topic_vectors
    topic_embedding = np.average(embeddings[i * n: n + (i * n)], weights=word_importance, axis=0)
  File "<__array_function__ internals>", line 200, in average
  File "/home/venv/lib/python3.9/site-packages/numpy/lib/function_base.py", line 539, in average
    raise ValueError(
ValueError: Length of weights not compatible with specified axis.`


I overcame this error by setting the top_n parameter identical in BERTopic and MaximalMarginalRelevancecall, as mentionned in #1054 and #1259.

**Comment by MaartenGr** [comment] 2023-06-01 08:40
@leoalz I think this might be resolved if you update BERTopic to the latest release, v0.15. I remember there was a fix for this in that release. Hopefully, that will help resolve your issue.

**Comment by fojackson8** [comment] 2023-12-20 11:38
From what I understand above, it seems the only way to get a list of top n words without retraining the model is to use the c_tf_idf matrix. Is this correct?

Assuming yes - one issue is the c_tf_idf matrix doesn't seem to be updated when you change representation_model. For example I'm using MMR to improve the diversity of keywords representing topics, but the top ranked terms in the c_tf_idf don't correspond to this list of maximally diverse keywords. They instead seem to correspond to the topic keywords before applying MMR, so there's lots of plurals or otherwise similar words, eg "forest" and "forests". Am I missing something here?

**Comment by MaartenGr** [comment] 2023-12-20 12:01
> From what I understand above, it seems the only way to get a list of top n words without retraining the model is to use the c_tf_idf matrix. Is this correct?

Yes and no. You can use `.update_topics` to re-run the c-TF-IDF calculation without the need to retrain the **entire** model. 

> but the top ranked terms in the c_tf_idf don't correspond to this list of maximally diverse keywords. 

That makes sense since c-TF-IDF and MMR are two different representations. When you run MMR, it should not change the c-TF-IDF representations but fine-tune them instead. 

> What I'd ideally like is a top n list of maximally diverse keywords, where I can choose n for different scenarios

There are `top_n` parameters both in `BERTopic()` as well as in `MaximalMarginalRelevance()` that you can tweak. Using the `.update_topics` function you can quickly choose a different `top_n` for certain scenarios.

**Comment by fojackson8** [comment] 2023-12-20 12:21
Thanks a lot for your quick response. 

Regarding your last point - from reading these discussions, it seems like we want to keep top_n_keywords for model training low, say around a max of 40 keywords when instantiating BERTopic, and 20 for the MMR reduction. 

It makes sense to summarise a topic with 20 keywords, but say we now want a list of top 500 keywords for each topic ranked, eg to check distinction between two similar topics or weed out unwanted words. How would we obtain this? Is there a way to get this list following the MMR ranking, or does MMR necessarily reduce n_keywords?

**Comment by MaartenGr** [comment] 2023-12-20 13:02
> Regarding your last point - from reading these discussions, it seems like we want to keep top_n_keywords for model training low, say around a max of 40 keywords when instantiating BERTopic, and 20 for the MMR reduction.

It can be more compute-intensive to generate more keywords but that is not necessarily an issue. If you want, you can generate 100 keywords when instantiating BERTopic and 50 or so for the MMR reduction.

> or does MMR necessarily reduce n_keywords?

Yes, the way MMR is implemented diversifies the keywords by filtering the words.

> How would we obtain this?

You could still create 500 keywords when instantiating BERTopic and use MMR as a separate representation model instead:

```python
from bertopic.representation import MaximalMarginalRelevance

representation_model = {
   "MMR": KeyBERTInspired(top_n_words=50)
}
topic_model = BERTopic(
    representation_model=representation_model, 
    top_n_words=500
)
```
