### ISSUE TITLE
AttributeError When Saving BERTopic Model

### ISSUE THREAD

**Issue by momodatascientist** [MaartenGr/BERTopic#1743] opened 2024-01-12 14:37 UTC
I am encountering an AttributeError when trying to save a BERTopic (v0.16.0) model that has been fitted with a ClassTfidfTransformer. This error occurs despite the model being successfully fitted with data.

**Error:**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-37-a471f925fc55> in <cell line: 5>()
      3 
      4 
----> 5 topic_model.save("/content/drive/MyDrive/BERTmodels/example_model", serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model_mpnet)

1 frames
/usr/local/lib/python3.10/dist-packages/bertopic/_bertopic.py in save(self, path, serialization, save_embedding_model, save_ctfidf)
   3009             # Additional
   3010             if save_ctfidf:
-> 3011                 save_utils.save_ctfidf(model=self, save_directory=save_directory, serialization=serialization)
   3012                 save_utils.save_ctfidf_config(model=self, path=save_directory / 'ctfidf_config.json')
   3013 

/usr/local/lib/python3.10/dist-packages/bertopic/_save_utils.py in save_ctfidf(model, save_directory, serialization)
    316                 serialization: str):
    317     """ Save c-TF-IDF sparse matrix """
--> 318     indptr = torch.from_numpy(model.c_tf_idf_.indptr)
    319     indices = torch.from_numpy(model.c_tf_idf_.indices)
    320     data = torch.from_numpy(model.c_tf_idf_.data)

AttributeError: 'NoneType' object has no attribute 'indptr'
```

**cTF-IDF config:**

```
ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=False,
                                     seed_words=["investment", "interest", "deposit", "earning", "currency", "saving", "bonus"], 
                                     seed_multiplier=2)
```

**BERTopic model config:**

```
topic_model = BERTopic(
    embedding_model=embedding_model_mpnet,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    zeroshot_topic_list=zeroshot_topic_list,
    zeroshot_min_similarity=.85,
    representation_model=main_representation,
    top_n_words=15,
    language='english',
    n_gram_range=(1,3),
    min_topic_size=10,
    calculate_probabilities=True
)

```

Any insights or suggestions to resolve this issue would be greatly appreciated. Thank you in advance!

**Comment by MaartenGr** [comment] 2024-01-12 14:48
Could you share your full code? It helps to see an end to end example since it might also be related to other parameters.

**Comment by momodatascientist** [comment] 2024-01-12 14:58
Thanks for the super quick response! Sharing the relevant code snippets

```
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, PartOfSpeech
from bertopic.representation import BaseRepresentation
from bertopic import BERTopic

zeroshot_topic_list = ["Investment in dollars", "No benefits","Platform appreciation",....]

embedding_model_mpnet = SentenceTransformer("all-mpnet-base-v2")
df.reset_index(drop=True, inplace=True)
embeddings = embedding_model_mpnet.encode(df['responses'], show_progress_bar=True)


umap_model = UMAP(n_neighbors=15, 
                  n_components=50,
                  min_dist=0.01,
                  metric='cosine',
                  random_state=42)


hdbscan_model = HDBSCAN(min_cluster_size=10, 
                        min_samples=7,
                        #alpha=1.2, 
                        gen_min_span_tree=True,
                        metric= 'euclidean',
                        cluster_selection_epsilon=0.25,
                        cluster_selection_method='leaf',
                        prediction_data=True)


vectorizer_model = TfidfVectorizer(ngram_range=(1, 3))


ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=False,
                                     seed_words=["investment", "interest", "deposit", "earning", "currency", "saving", "bonus"], 
                                     seed_multiplier=2)


main_representation = KeyBERTInspired()


topic_model = BERTopic(
    embedding_model=embedding_model_mpnet,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    zeroshot_topic_list=zeroshot_topic_list,
    zeroshot_min_similarity=.85,
    representation_model=main_representation,
    top_n_words=15,
    language='english',
    n_gram_range=(1,3),
    min_topic_size=10,
    calculate_probabilities=True
)


docs = df['responses']
topics, probs = topic_model.fit_transform(docs, embeddings)
```

**Saving the model**
```
from google.colab import drive
drive.mount('/content/drive')

topic_model.save("/content/drive/MyDrive/BERTmodels/example_model", serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model_mpnet)
```

**Comment by MaartenGr** [comment] 2024-01-13 06:37
Although I am not sure what the issue is, there are a couple of things you can try:

* Remove `main_representation` as it might overwrite the c-TF-IDF representation
* Remove `ctfidf_model` to see whether some hyperparameters affect saving it
* Making sure that `docs` is a list of strings and not a pandas series (which it is now)
* You are using `TfidfVectorizer` which is **not** advised and might break things since a Bag-of-Words model is expected there. Imagine doing TF-IDF first and then applying c-TF-IDF instead of Bag-of-Words and then c-TF-IDF, see where that goes wrong?

**Comment by momodatascientist** [comment] 2024-01-13 07:42
Hi @MaartenGr Thank you for the suggestions, especially the 4th one! 

Somehow these didn't help fix the error. I was able to successfully save the model on commenting out the zero shot learning code. Am I missing anything here?

```
topic_model = BERTopic(
    ....
    #zeroshot_topic_list=zeroshot_topic_list,
    #zeroshot_min_similarity=.85,
    ....
)
```

**Comment by MaartenGr** [comment] 2024-01-13 10:17
Ah right! With zero-shot topic modeling through the use of the `zeroshot_topic_list` parameter, you are essentially merging topic models but their c-TF-IDF representations do not get merged (since they contain different vocabularies). So saving the c-TF-IDF matrices is not possible unless you recalculate them from scratch. 

Something like this might work before saving the model:

```python
documents = pd.DataFrame({"Document": docs, "Topic": topics, "ID": range(len(docs)), "Image": None})
documents_per_topic = documents.groupby(['Topic'], as_index=False).agg({'Document': ' '.join})
topic_model.c_tf_idf_, words = topic_model._c_tf_idf(documents_per_topic)
```

Note that `docs` is a list of strings and refer to your input.

**Closed** 2024-01-19 04:18 UTC
