### ISSUE TITLE
MultiModalBackend throws error with clip-ViT-B-32-multilingual-v1

### ISSUE THREAD

**Issue by 02** [MaartenGr/BERTopic#1668] opened 2023-12-06 13:22 UTC
The MultiModalBackend works with clip-ViT-B-32, but throws an error for the multilingual version. 

`MultiModalBackend("clip-ViT-B-32-multilingual-v1",batch_size=32)`

```
AttributeError                            Traceback (most recent call last)
[/Users/petter/My](https://file+.vscode-resource.vscode-cdn.net/notebook.ipynb Cell 92 line 1
     [14](vscode-notebook-cell:notebook.ipynb#Y260sZmlsZQ%3D%3D?line=13) from bertopic import BERTopic
     [15](vscode-notebook-cell:notebook.ipynb#Y260sZmlsZQ%3D%3D?line=14) from bertopic.representation import VisualRepresentation
---> [17](vscode-notebook-cell:notebook.ipynb#Y260sZmlsZQ%3D%3D?line=16) model = MultiModalBackend("clip-ViT-B-32-multilingual-v1",batch_size=32)

File [/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:56](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:56), in MultiModalBackend.__init__(self, embedding_model, batch_size)
     [51](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:51) else:
     [52](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:52)     raise ValueError("Please select a correct SentenceTransformers model: \n"
     [53](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:53)                      "`from sentence_transformers import SentenceTransformer` \n"
     [54](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:54)                      "`model = SentenceTransformer('clip-ViT-B-32')`")
---> [56](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:56) self.tokenizer = self.embedding_model._first_module().processor.tokenizer

File [/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py:1695](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py:1695), in Module.__getattr__(self, name)
   [1693](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py:1693)     if name in modules:
   [1694](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py:1694)         return modules[name]
-> [1695](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py:1695) raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'Transformer' object has no attribute 'processor'
```

I've tried reinstalling everything.

Versions:
- sentence-transformers==2.2.2
- transformers==4.35.2
- bertopic==0.16.0
- python 3.11

**Comment by 02** [comment] 2023-12-06 13:25
I tried modifying the in _multimodal.py:56 to 
`self.tokenizer = self.embedding_model.tokenizer` 
which helped for that line, but it still crashed at a later point.

**Comment by MaartenGr** [comment] 2023-12-06 18:10
Could you perhaps share your full code or a reproducible example? That way, I can test out what exactly is going wrong here.

**Comment by 02** [comment] 2023-12-06 18:20
Sure, here is the complete code to reproduce the problem:

```
from bertopic.backend import MultiModalBackend
model = MultiModalBackend('clip-ViT-B-32-multilingual-v1', batch_size=32)

```

:)

**Comment by 02** [comment] 2023-12-06 21:22
Now it’s working! Amazing, thanks so much!
(I think it was version 1670 though.)

**Comment by MaartenGr** [comment] 2023-12-07 16:33
Hmmm, that's odd but it might be related to your input images. Could you make sure that the input images are all in the same format as shown in the [example](https://maartengr.github.io/BERTopic/getting_started/multimodal/multimodal.html)? Also, if you have the time, do the datasets in that example work with the multilingual? Other than that, it seems to be an issue related to sentence-transformers, so it might be worthwhile to also open up an issue there.

**Comment by 02** [comment] 2023-12-08 09:49
Here is a complete code example to reproduce the error, based on changing the example in your link to use the multilingual model. It uses the dataset in that example. It works when using the non-multilingual model. 

```
from datasets import load_dataset
from bertopic.backend import MultiModalBackend
ds = load_dataset("maderix/flickr_bw_rgb")
images = ds["train"]["image"]
docs = ds["train"]["caption"]
model = MultiModalBackend('clip-ViT-B-32-multilingual-v1', batch_size=32)
doc_image_embeddings = model.embed(docs, images)
```

```
TypeError                                 Traceback (most recent call last)
[/Users/petter/My](https://file+.vscode-resource.vscode-cdn.net/Users/petter/My) Drive/PAPERS/CURRENT/2023 project anton/climate anal.ipynb Cell 113 line 7
      [5](vscode-notebook-cell:/...ayayay.ipynb#Y244sZmlsZQ%3D%3D?line=4) docs = ds["train"]["caption"]
      [6](vscode-notebook-cell:...ayayay.ipynb#Y244sZmlsZQ%3D%3D?line=5) model = MultiModalBackend('clip-ViT-B-32-multilingual-v1', batch_size=32)
----> [7](vscode-notebook-cell:...ayayay.ipynb#Y244sZmlsZQ%3D%3D?line=6) doc_image_embeddings = model.embed(docs, images)

File [/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:86](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:86), in MultiModalBackend.embed(self, documents, images, verbose)
     [84](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:84) image_embeddings = None
     [85](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:85) if isinstance(images, list):
---> [86](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:86)     image_embeddings = self.embed_images(images, verbose)
     [88](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:88) # Average embeddings
     [89](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:89) averaged_embeddings = None

File [/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:144](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:144), in MultiModalBackend.embed_images(self, images, verbose)
    [141](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:141) end_index = (i * self.batch_size) + self.batch_size
    [143](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:143) images_to_embed = [Image.open(image) if isinstance(image, str) else image for image in images[start_index:end_index]]
--> [144](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:144) img_emb = self.embedding_model.encode(images_to_embed, show_progress_bar=False)
    [145](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:145) embeddings.extend(img_emb.tolist())
    [147](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/bertopic/backend/_multimodal.py:147) # Close images

File [/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:161](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:161), in SentenceTransformer.encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    [159](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:159) for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    [160](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:160)     sentences_batch = sentences_sorted[start_index:start_index+batch_size]
--> [161](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:161)     features = self.tokenize(sentences_batch)
    [162](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:162)     features = batch_to_device(features, device)
    [164](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:164)     with torch.no_grad():

File [/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:319](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:319), in SentenceTransformer.tokenize(self, texts)
    [315](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:315) def tokenize(self, texts: Union[List[str], List[Dict], List[Tuple[str, str]]]):
    [316](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:316)     """
    [317](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:317)     Tokenizes the texts
    [318](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:318)     """
--> [319](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:319)     return self._first_module().tokenize(texts)

File [/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:102](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:102), in Transformer.tokenize(self, texts)
    [100](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:100) batch1, batch2 = [], []
    [101](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:101) for text_tuple in texts:
--> [102](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:102)     batch1.append(text_tuple[0])
    [103](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:103)     batch2.append(text_tuple[1])
    [104](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py:104) to_tokenize = [batch1, batch2]

TypeError: 'JpegImageFile' object is not subscriptable
```

**Comment by MaartenGr** [comment] 2023-12-08 10:52
Alright, I just tested some things out and apparently, it seems that the multilingual model is only multilingual from a text perspective. This means that the text encoder can create multilingual representations that are separate from the image embeddings. In other words, two different models. 

If you check out the example [here](https://huggingface.co/sentence-transformers/clip-ViT-B-32-multilingual-v1) it shows that the load in the `'clip-ViT-B-32'` model for encoding the images and `'clip-ViT-B-32-multilingual-v1'` for encoding text. Since BERTopic assumes a single model for encoding both text and images, this does not work. 

I just pushed a fix to #1670 which should hopefully resolve the issue. Could you test it out? This is working for me:

```python
from datasets import load_dataset
from bertopic.backend import MultiModalBackend

# Data
ds = load_dataset("maderix/flickr_bw_rgb")
images = ds["train"]["image"][:100]
docs = ds["train"]["caption"][:100]

# Model to embed images and to embed multilingual text
model = MultiModalBackend(embedding_model='clip-ViT-B-32-multilingual-v1', image_model='clip-ViT-B-32', batch_size=32)

# Embed documents only
doc_embeddings = model.embed_documents(docs, verbose=True)

# Embeding images only
image_embeddings = model.embed_images(images, verbose=True)

# Embed both images and documents, then average them
doc_image_embeddings = model.embed(docs, images, verbose=True)
```

**Comment by 02** [comment] 2023-12-09 18:28
Ah, that explains the problems, and explains why sentence_transformer loads the two differently! 

Great, thanks for this. It got past the line, but crashed when creating the model. I found the problem though: since doc_image_embeddings is a list (or something), line 227 of bertopic needs to be changed from:

`self.language = language if not embedding_model else None`

to

`self.language = language if embedding_model is not None else None`

After I changed that, the entire analysis seems to be working. Yay! (Will report back when I see if the results make sense. :)

**Comment by MaartenGr** [comment] 2023-12-09 19:02
@02 Could you share the full code? That way, I can verify why that line needs to be changed.

**Comment by 02** [comment] 2023-12-10 00:18
Sure, this should do it:

```
from datasets import load_dataset
from bertopic.backend import MultiModalBackend
ds = load_dataset("maderix/flickr_bw_rgb")
images = ds["train"]["image"][:100]
docs = ds["train"]["caption"][:100]
model = MultiModalBackend(embedding_model='clip-ViT-B-32-multilingual-v1', image_model='clip-ViT-B-32', batch_size=32)
doc_embeddings = model.embed_documents(docs, verbose=True)
image_embeddings = model.embed_images(images, verbose=True)
doc_image_embeddings = model.embed(docs, images, verbose=True)
visual_model = VisualRepresentation(image_height=600,image_squares=True)
representation_model = {
   "Visual_Aspect":  visual_model,
}
topic_model = BERTopic(representation_model=representation_model, embedding_model=doc_image_embeddings, verbose=True)
topics, probs = topic_model.fit_transform(documents=docs, images=images, embeddings=doc_image_embeddings)

```

**Comment by stay-leave** [comment] 2023-12-10 12:09
Hello! Thank you very much for your project. I encountered some issues while working on a multimodal project.
```
model = MultiModalBackend(embedding_model='clip-ViT-B-32-multilingual-v1', image_model='clip-ViT-B-32',  batch_size=32)
TypeError: MultiModalBackend.__init__() got an unexpected keyword argument 'image_model'
```
when i try this code, found
```
model = MultiModalBackend(embedding_model='clip-ViT-B-32-multilingual-v1',  batch_size=32)
AttributeError: 'Transformer' object has no attribute 'processor'
```
However,  when i don't use the embedding_model,  it seems right. 
![image](https://github.com/MaartenGr/BERTopic/assets/58450966/8e0c5408-b3a0-4242-839c-77a75f9be66c)

Representation is this:

![image](https://github.com/MaartenGr/BERTopic/assets/58450966/3ae55fe5-3e63-4c86-8bbc-5938fbe9eadc)

My text is in Chinese, and it contains many numbers which have been identified as topic words, but not the Chinese characters. Previously, I did not perform word segmentation; the texts are in a list (each element being a sentence), and images are also in a list (each containing paths). May I ask what could be the reason for this issue? Below are the details of my environment:
bertopic 0.16.0
transformers 4.32.0
sentence-transformers 2.2.2
Python 3.10.11

**Comment by stay-leave** [comment] 2023-12-11 03:46
Additionally, how to model a sentence with multiple images?  Thanks!

**Comment by MaartenGr** [comment] 2023-12-11 12:56
@02 It seems that you made a mistake in your code. You should not pass the embeddings to `embedding_model` but the embedding model itself. In other words, don't do this:

```python
topic_model = BERTopic(representation_model=representation_model, embedding_model=doc_image_embeddings, verbose=True)
```

but do this:

```python
topic_model = BERTopic(representation_model=representation_model, embedding_model=model, verbose=True)
```

@stay-leave You should install BERTopic from the fix in #1670. That way, it should have the `image_model` parameter.

> Additionally, how to model a sentence with multiple images? Thanks!

You can't do that directly in BERTopic. However, you could simply duplicate the sentences and pass a single image for each image.

**Comment by stay-leave** [comment] 2023-12-11 13:44
> @02 It seems that you made a mistake in your code. You should not pass the embeddings to `embedding_model` but the embedding model itself. In other words, don't do this:
> 
> ```python
> topic_model = BERTopic(representation_model=representation_model, embedding_model=doc_image_embeddings, verbose=True)
> ```
> 
> but do this:
> 
> ```python
> topic_model = BERTopic(representation_model=representation_model, embedding_model=model, verbose=True)
> ```
> 
> @stay-leave You should install BERTopic from the fix in #1670. That way, it should have the `image_model` parameter.
> 
> > Additionally, how to model a sentence with multiple images? Thanks!
> 
> You can't do that directly in BERTopic. However, you could simply duplicate the sentences and pass a single image for each image.

thanks! I run it successful!

**Comment by aysedeniz09** [comment] 2023-12-12 00:01
Also getting the same error with model = MultiModalBackend(embedding_model='clip-ViT-B-32', batch_size=32)

the code:

model = MultiModalBackend(embedding_model='clip-ViT-B-32', batch_size=32)
doc_image_embeddings = model.embed(docs, filtered_images)
visual_model = VisualRepresentation(image_height=600,image_squares=True)
representation_model = {
   "Visual_Aspect":  visual_model,
}
topic_model = BERTopic(representation_model=representation_model, embedding_model=doc_image_embeddings, verbose=True)
topics, probs = topic_model.fit_transform(documents=docs, images=filtered_images, embeddings=doc_image_embeddings)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/local_scratch/pbs.1693717.pbs02/ipykernel_2929980/3413361212.py in <module>
      6 
      7 print("Topic Model with our images")
----> 8 topic_model = BERTopic(representation_model=representation_model, embedding_model=doc_image_embeddings, verbose=True)
      9 
     10 print("Image and Text Embedding Model Complete")

~/.local/lib/python3.9/site-packages/bertopic/_bertopic.py in __init__(self, language, top_n_words, n_gram_range, min_topic_size, nr_topics, low_memory, calculate_probabilities, seed_topic_list, zeroshot_topic_list, zeroshot_min_similarity, embedding_model, umap_model, hdbscan_model, vectorizer_model, ctfidf_model, representation_model, verbose)
    225 
    226         # Embedding model
--> 227         self.language = language if not embedding_model else None
    228         self.embedding_model = embedding_model
    229 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Name: sentence-transformers
Version: 2.2.2
Name: bertopic
Version: 0.16.0
Name: transformers
Version: 4.34.0
python 3.9

**Comment by MaartenGr** [comment] 2023-12-12 05:29
@aysedeniz09 Check my [comment above](https://github.com/MaartenGr/BERTopic/issues/1668#issuecomment-1850107221). The code you copied has an issue.

**Comment by 02** [comment] 2023-12-12 06:58
Ah yes, thank you @MaartenGr, and apologies for my mistake. The code runs now, but it seems like it is not correctly applying the multilingual model on the text. I get the same result as when applying the clip-ViT-B-32 model on Swedish: 
it is removing all special characters (like å, ä, ö) and the topics are full of stopwords. 

I think I'm gonna give up and just translate everything to English and use the clip-ViT-B-32 model.

**Comment by MaartenGr** [comment] 2023-12-12 07:04
@02 I believe that might be a result of the underlying [`CountVectorizer`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html). Make sure that it is not removing those special characters. Lastly, using a representation model, like [KeyBERTInspired](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#keybertinspired), tends to remove stopwords.

**Comment by 02** [comment] 2023-12-12 08:03
Thank you. Just a question about the representation model, how do I use KeyBERTInspired when I'm also using a visual aspect model? Can't find this mentioned in the documentation. After reading the source code, I tried the following, but it didn't seem to work:

```
representation_model = {
   "Visual_Aspect":  visual_model,
   "Main": KeyBERTInspired()
}
```

**Comment by MaartenGr** [comment] 2023-12-12 08:32
> After reading the source code, I tried the following, but it didn't seem to work:

What do you mean by "it didn't seem to work"? Could you be a bit more specific in what the issue seems to be?

**Comment by 02** [comment] 2023-12-12 08:39
Sorry. It ran but it did not remove any stopwords and had no discernible effect whatsoever. On 12 Dec 2023, at 09:32, Maarten Grootendorst ***@***.***> wrote:﻿

After reading the source code, I tried the following, but it didn't seem to work:

What do you mean by "it didn't seem to work"? Could you be a bit more specific in what the issue seems to be?

**Comment by MaartenGr** [comment] 2023-12-12 09:08
@02 The following is working without any problems for me, including stop word removal through KeyBERTInspired:

```python
from datasets import load_dataset
from bertopic.backend import MultiModalBackend
from bertopic.representation import VisualRepresentation, KeyBERTInspired
from bertopic import BERTopic
from umap import UMAP

# Data
ds = load_dataset("maderix/flickr_bw_rgb")
images = ds["train"]["image"][:100]
docs = ds["train"]["caption"][:100]

# Embed both documents and images
embedding_model = MultiModalBackend(embedding_model='clip-ViT-B-32-multilingual-v1', image_model='clip-ViT-B-32', batch_size=32)
embeddings = embedding_model.embed(docs, images, verbose=True)

# Representation models
representation_models = {
   "Visual_Aspect":  VisualRepresentation(image_height=600, image_squares=True),
   "KeyBERTInspired": KeyBERTInspired()
}

# Fit BERTopic
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
topic_model = BERTopic(representation_model=representation_models, embedding_model=embedding_model, verbose=True)
topics, probs = topic_model.fit_transform(documents=docs, images=images, embeddings=embeddings)
```

**Comment by 02** [comment] 2023-12-12 09:57
Maybe I'm being daft here, but when I run that exact code, the topics I get seem to be full of stopwords:

> 0: "of, photograph, and, the"
> 1: "dog, of, ..., the"

Am I missing something? (And thanks so much for your support and patience!)

**Comment by MaartenGr** [comment] 2023-12-12 10:03
@02 No problem! Any question is a good question.

When you run `topic_model.get_topic_info()`, you will see three representations. The main representation that indeed contains the stopwords, the visual representation, and the KeyBERTInspired representation. 

BERTopic is able to generate many representations of a single topic since you might want to view a topic from different angles.

To access these different representations you can either run `topic_model.get_topic_info()` or run `topic_model.get_topics(full=True)` to get the full representations.

**Closed** 2023-12-22 17:07 UTC
