### ISSUE TITLE
Segfaults on Apple M1 Chip

### ISSUE THREAD

**Issue by boscacci** [MaartenGr/BERTopic#112] opened 2021-04-30 16:47 UTC
I realize that porting for ARM architecture is likely not a super high priority, but I am experiencing repeated C++ segfaults when training a BERTopic model on an Apple M1 chip and thought I'd mention it here:

## Expected Behavior
Training BERTopic model completes regardless of input size

## Actual Behavior

If input size is more than a couple hundred samples (where one sample is a string ~400 chars in length), then midway through `fit_transform`, I get this output:

`/opt/homebrew/Caskroom/miniforge/base/envs/butter/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown`

And my jupyter kernel dies.

## Steps to Reproduce the Problem

0. Get set up on an Apple Silicone dev environment
1. `model = BERTopic(language='english', embedding_model="distilbert-base-nli-mean-tokens", calculate_probabilities=True, verbose=True, nr_topics="auto")`
2. `model.fit_transform(list_of_input_strings_or_maybe_a_pandas_series)`

## Specifications
![image](https://user-images.githubusercontent.com/12357390/116727081-19f9b480-a9b2-11eb-8ce2-3213fc021852.png)

## What's been tried so far
* Running the same code as a .py script outside of Jupyter notebook yielded the same error but with an added "segmentation fault" message
* Updating miniforge did not help
* Creating a new Python 3.8.6 conda env, reinstalling some of BERTopic's dependencies with conda (and BERTopic with pip) and running it there did not help
* Running the same code with the same data on an intel-based Mac (with twice the RAM) works.

**Comment by MaartenGr** [comment] 2021-05-01 05:54
Thank you for the extensive issue report. I cannot be sure, but since you report that it might be due to the sample length it could be attributed to `sentence-transformers`. It might be interesting to try `Flair` instead and see if that fixes your issue. Since you set verbose to True, can you pinpoint what steps it had already finished before you got the error? In other words, does this issue happen before, during, or after the embeddings were generated? 

Also, now that I think about it, if it is indeed an issue with embeddings then you could create them beforehand and simply pass them to `fit_transform`.

**Comment by boscacci** [comment] 2021-05-03 13:57
Yeah, it fails whilst generating embeddings a la SentenceTransformer `model.encode()` .

I tried installing `flair`, but I am unable to run this: `from flair.embeddings import TransformerDocumentEmbeddings` because it results in `AttributeError: type object 'gensim._matutils.array' has no attribute '__reduce_cython__'`

So I will stick to my x86 machine over ssh for now. Happy to keep trying things

**Comment by MaartenGr** [comment] 2021-05-20 17:20
I am going to close this for now. However, if you find a fix or want to continue with the discussion, feel free to reopen it!

**Closed by MaartenGr** 2021-05-20 17:20 UTC

**Comment by boscacci** [comment] 2021-07-02 16:07
This problem magically went away. I don't know what changed. Sorry to bother!

**Comment by vishhvak** [comment] 2021-11-05 21:03
How do you install bertopic on Apple silicon?

**Comment by boscacci** [comment] 2022-02-24 22:44
@vishhvak—first step, get set up with conda forge: https://conda-forge.org/

Make a new conda env, and install the conda-forge versions of bertopic's dependencies. This can be done in a one-liner:

`conda create -n YOUR_NEW_ENV python=3.9 numpy hdbscan pandas umap-learn scikit-learn tqdm sentence-transformers plotly==4.7.0 pyyaml`

Activate that env:

`conda activate YOUR_NEW_ENV`

Now just pip install as others would:

`pip install bertopic`

**Comment by justinchuntingho** [comment] 2022-05-24 10:11
I am afriad the above instuction no longer works since I got a legacy-install-failure for numba.

I am running on a M1 Mac (MacOS Big Sur 11.4)

**Comment by ArtemBernatskyy** [comment] 2022-10-08 20:09
Macbook is sh#$t, don't buy it. Got this error on Macbook 14 (2021). Monterey 12.6, Python 3.9.13.

I will throw away this useless notebook and will buy some linux laptop, that's enoght...

**Comment by ifly6** [comment] 2024-04-11 14:47
I'm getting a segmentation fault:

```
tokenizer_config.json: 100%...
config.json: 100%...
vocab.json: 100%...
merges.txt: 100%...
tokenizer.json: 100%...
model.safetensors: 100%...
zsh: segmentation fault  python 1_bertopic.py
```

When running with `flair`:

```
from bertopic import BERTopic
from flair.embeddings import TransformerDocumentEmbeddings

docs = ...
model = BERTopic()

roberta = TransformerDocumentEmbeddings('roberta-base')
topic_model = BERTopic(embedding_model=roberta, verbose=True)
topics, probs = model.fit_transform(docs)
```

This is perhaps an improvement over stock which immediately gets a segmentation fault on initialisation. I guess for me the problem isn't magically non-existent. I'm also running on M2 if that's relevant.

**Comment by MaartenGr** [comment] 2024-04-14 06:17
@ifly6 I believe [this thread](https://github.com/MaartenGr/BERTopic/issues/1842) and [this PR](https://github.com/MaartenGr/BERTopic/pull/1854) might be relevant for you. Please take a look!

**Comment by Qiuzhuang** [comment] 2024-11-16 14:40
I run into this issue in my Mac Intel. After changing init from '**spectral**' by default to '**random**', it works well now.  I guess that spectral would consume huge memory as its O(n^2). I tune doc size to be small enough and use spectral, it doesn't lead to 
Segfaults. 
`
umap_model = UMAP(init="**random**", n_components=5, n_neighbors=200, metric="cosine", random_state=42, verbose=True)
`
