### ISSUE TITLE
Saving BerTopic into file issue

### ISSUE THREAD

**Issue by sanjugahara** [MaartenGr/BERTopic#482] opened 2022-03-24 17:21 UTC
Hi Maarten,
Thanks for your comprehensive and prompt response to #370 
Now, we are on the latest version of BerTopic and we are still facing issues with save and load models.

There is no problem for saving and loading the model without clearing the cache in memory:
```
# Save and load model without clearing the cache in memory
topic_model.save("my_model")
my_model = BERTopic.load("my_model")
```
The outcomes of the saved and loaded model agains same data input are equivalent.

But when we were trying to 
1. Save the model, clear the memory cache, and reload the model
Or 
2. Save the model to a file path and reload it later from different kernel 
```
# Save and load model with clearing cache
topic_model.save("xxx/xxx/localfolder")
#Clear cache or restart kernel
my_model = BERTopic.load("xxx/xxx/localfolder")
```
The outcomes of the saved and loaded model agains same data input are NOT equivalent. And values does not make sense (topic probability very small < 0.05)

Would it be possible something was not saved by the .save() function. It looks like the loaded model reused something in the memory(like the umap model?).

Thank you in advance!

**Comment by MaartenGr** [comment] 2022-03-25 10:09
Could you share the code for how you have tested the equivalence of input and output? Could you share a reproducible example? To me, it is not exactly clear what you mean with:

> The outcomes of the saved and loaded model agains same data input are NOT equivalent.

Are the outcomes generated when you run `.transform()` using the same input data?

**Comment by sanjugahara** [comment] 2022-03-25 16:14
> Could you share the code for how you have tested the equivalence of input and output? Could you share a reproducible example? To me, it is not exactly clear what you mean with:
> 
> > The outcomes of the saved and loaded model agains same data input are NOT equivalent.
> 
> Are the outcomes generated when you run `.transform()` using the same input data?

Thanks for the reply!!

This would be the code how we do it:
``` 
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Set the random state in the UMAP model to prevent stochastic behavior 
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)

# Train model
topic_model = BERTopic(umap_model=umap_model, verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings)

# Transform same documents and check if the predicted topics are the same
new_topics, new_probs = topic_model.transform(docs, embeddings)
assert topics == new_topics

# Save and load model
topic_model.save("my_model")
my_model = BERTopic.load("my_model")
new_topics, new_probs = my_model.transform(docs, embeddings)
assert topics == new_topics
```

**Comment by MaartenGr** [comment] 2022-03-26 07:22
Thank you for the extensive description. Unfortunately, I cannot seem to replicate the issue in a Google Colab instance. 

First, I install BERTopic through `!pip install bertopic`, then I train and save the model (including topics) as follows:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP
import pickle

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Set the random state in the UMAP model to prevent stochastic behavior 
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)

# Train model
topic_model = BERTopic(umap_model=umap_model, verbose=True)
topics, probs = topic_model.fit_transform(docs, embeddings)

# Transform same documents and check if the predicted topics are the same
new_topics, new_probs = topic_model.transform(docs, embeddings)
assert topics == new_topics

# Save and load model
topic_model.save("my_model")
my_model = BERTopic.load("my_model")
new_topics, new_probs = my_model.transform(docs, embeddings)
pickle.dump(topics, open( "topics.pickle", "wb" ) )
assert topics == new_topics
```

Then, I completely reset the Google Colab instance and run the following after having uploaded `my_model` and `topics.pickle` to the instance:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from umap import UMAP
import pickle

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Load saved instances
my_model = BERTopic.load("my_model")
topics = pickle.load( open( "topics.pickle", "rb" ) )

# Extract new topics and compare with the previously saved topics
new_topics, new_probs = my_model.transform(docs, embeddings)
assert topics == new_topics
```

The topics stay exactly the same in my environment. Did you perhaps change environments between saving and loading the model?

**Comment by sanjugahara** [comment] 2022-03-29 17:16
Hi Maarten,
Could you try to completely reset the Google Colab instance,
and the ran .transform using the same data set and compare the new topics with the original outcomes?
Steps:
1. In the first instance, run fit_transform and save the model.
2. Start a new instance, load the model and run transform, then compare the topics between before and after.
Thanks a lot!!

**Comment by eyang9002** [comment] 2022-03-30 04:24
I will add that I too am having issues with consistency when transforming with a previously saved and loaded model. After loading the model and passing in **the same input** 200 times, I am getting not only inconsistent probabilities for each transformation, but ~54% of them get classified as -1.

**Comment by eyang9002** [comment] 2022-03-30 04:28
Another way that I have tested this is by transforming the same data that was used to train the model originally. And I get a different number of documents that get classified as -1.

**Comment by MaartenGr** [comment] 2022-03-30 07:11
@sanjugahara 

> Could you try to completely reset the Google Colab instance,
and the ran .transform using the same data set and compare the new topics with the original outcomes?
Steps:
> 1. In the first instance, run fit_transform and save the model.
> 2. Start a new instance, load the model and run transform, then compare the topics between before and after.
Thanks a lot!!

Yes, that is exactly what I did in the code that I posted directly above yours. In the first instance, I ran `fit_transform` and saved the model as well as the topics that were generated. Then, I started a completely new instance, loaded the model as well as the topics that were generated in the previous instance, ran `.transform()` and I get the exact same topics. 

@eyang9002 

> After loading the model and passing in the same input 200 times, I am getting not only inconsistent probabilities for each transformation, but 53% of them got classified as -1.

From your description it seems that you did not have set the `random_state` in UMAP as you should not get different probabilities for each transformation. Could you share your code for training, saving, and loading the model?

**Comment by eyang9002** [comment] 2022-03-30 18:49
@MaartenGr here is the code that I've been using, please note that I use pre-saved transformers, but I include the embedding model when saving the bertopic model. Additionally, like @sanjugahara, I load the model in a separate environment, so nothing is cached.

```
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
import hdbscan
import umap
import numpy as np
import pandas as pd


# Training
# Presaved transformers downloaded from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/
transformer_path = './path/to/presaved/transformer'
bert_transformer = SentenceTransformer(transformer_path)

hdbscan_model = hdbscan.HDBSCAN(min_cluster_size=10,
                                metric='euclidean',
                                cluster_selection_method='eom',
                                prediction_data=True,
                                gen_min_span_tree=True,
                               min_samples = 10)

umap_model = umap.UMAP(n_neighbors=15,
                                     n_components=5,
                                     min_dist=0.0,
                                     metric='cosine',
                                     low_memory=False,
                                     random_state=42)

bert_model = BERTopic(embedding_model=bert_transformer, 
                      verbose=True, 
                      hdbscan_model=hdbscan_model,
                      umap_model=umap_model,
                      top_n_words=10,
                      min_topic_size=10,
                      n_gram_range=(1, 3),
                      seed_topic_list=None
                     )
        
bert_model.calculate_probabilities = True

bert_topics, bert_probs = bert_model.fit_transform(train_data)

# Saving
bert_model.save('./path/to/model')

# Loading
loaded_model = BERTopic.load('./path/to/model')

predict_topics, predict_probs = loaded_model.transform(train_data)
```

**Comment by eyang9002** [comment] 2022-03-30 18:55
I use the same docker image for training and inference, so the dependencies should be the same. Here are the dependencies:

```
FROM python:3.7-buster

MAINTAINER Amazon AI <sage-learner@amazon.com>

RUN apt-get -y update && apt-get install -y --no-install-recommends \
         wget \
         python3-pip \
         python3-setuptools \
         nginx \
         ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN python --version

# Here we get all python packages.
# There's substantial overlap between scipy and numpy that we eliminate by
# linking them together. Likewise, pip leaves the install caches populated which uses
# a significant amount of space. These optimizations save a fair amount of space in the
# image, which reduces start up time.
# numba version 0.53.1 and numpy version 1.21.1 are required for semi-supervised functionality
RUN pip --no-cache-dir install \
        numpy>=1.21.1 \
        numba>=0.53.1 \
        scipy \
        pandas>=1.1.5 \
        openpyxl \
        flask \
        gunicorn \
        PyAthena \
        tweet-preprocessor==0.6.0 \
        ekphrasis==0.5.1 \
        sagemaker \
        sentence-transformers==2.1.0 \
        sklearn \
        scikit-learn>=1.0.1 \
        scipy \
        hdbscan>=0.8.27 \
        bertopic==0.9.4 
```

**Comment by MaartenGr** [comment] 2022-03-31 06:41
Reading through your code and some issues mentioned on the HDBSCAN repo, the only thing that I can think of is that setting `calculate_probabilities=True` might generate less accurate probabilities compared to the flat probabilities. Setting that to False might improve the stability of the results.

**Comment by eyang9002** [comment] 2022-04-01 16:08
@MaartenGr Unfortunately `calculate_probabilities` is not the culprit. I tried a couple of permutations of that setting to True/False when training & transforming and even when it is set to `False` the entire time, the transformations are still inconsistent.

**Comment by MaartenGr** [comment] 2022-04-02 06:36
Hmmm, reading through the HDBSCAN repo some more and it might be related to `approximate_predict` which, like the name implies, makes an approximation rather than an "exact" prediction. It might be interesting to not use a custom HDBSCAN model and leave that parameter empty to see if it improves the stability. Other than that, I am having trouble identifying what is exactly happening here...

**Comment by eyang9002** [comment] 2022-04-08 18:33
@MaartenGr I tried not using a custom model when creating a BerTopic model (main difference being `gen_min_span_tree` not being set to `True`). But the outcome was no different.

When you say not using a custom HDBSCAN model, do you mean taking the default HDBSCAN model BerTopic creates in __init__? Or are you suggesting passing in a HDBSCAN model that has no parameters specified? Do you have an idea of which parameters being set by default in BerTopic is the potential culprit?

**Comment by eyang9002** [comment] 2022-04-08 21:42
I've also tried training a model using Bertopic's default values and inference on the same input 200 times still results in inconsistent predictions.. I'll try doing this in colab. Have you been able to reproduce this issue @MaartenGr ?

**Comment by MaartenGr** [comment] 2022-04-10 05:55
> I've been able to reproduce this in colab as well. Have you been able to reproduce this issue @MaartenGr ?

Thus far, I have not been able to reproduce the issue. To me, if I input the same data as it was trained on then the results stay the same and are also stable across runs. Could you share the exact code for reproducing this also in Google colab? 

> When you say not using a custom HDBSCAN model, do you mean taking the default HDBSCAN model BerTopic creates in init? Or are you suggesting passing in a HDBSCAN model that has no parameters specified? Do you have an idea of which parameters being set by default in BerTopic is the potential culprit?

I indeed meant not defining a HDBSCAN model yourself and just letting BERTopic define the model. So ignoring the `hdbscan_model` parameter.  However, I am not entirely sure which parameters could result in this issue. As mentioned before, I do think that `.approaximate_predict()` might be part of the issue here as there is a chance it will not generate the same output as when you fit the instance. Having said that, it should still be a stable approximation and there should not be a difference between runs. That points towards UMAP being a stochastic algorithm but it is surprising as you did used a `random_state` for that model.

**Comment by recurrence** [comment] 2022-05-23 00:20
I've also been running into this BERTopic results differ after load problem.  I've managed to work with it by running a transform loop that continually reloads the model until it returns a good result.  However, I suspect this will not hold up in production.

In my case calculate_probabilities is False (due to the ram explosion from having almost a million documents) and I use pre saved embeddings.

**Comment by MaartenGr** [comment] 2022-07-13 08:12
Since this was active a while ago, I am going ahead and will close this issue. If, however, you want to re-open this issue, please let me know!

**Closed by MaartenGr** 2022-07-13 08:12 UTC
