### ISSUE TITLE
[ GPU Bertopic] std::bad_alloc: out_of_memory: CUDA error

### ISSUE THREAD

**Issue by Thiziri-Hafir** [MaartenGr/BERTopic#922] opened 2023-01-11 12:48 UTC
Hello, I've been using GPU acceleration of Bertopic for a while and it worked well. But I'm currently facing a problem even though I didn't change anything in my env or data except cuml version which is now 22.12. 

- Bertopic v0.13
- cudatoolkit v11.5.1
- cuml v22.12
- hdbscan v0.8.29  

![image](https://user-images.githubusercontent.com/72195389/211807965-fdd2c320-925f-44d5-b4d6-7e27b19f175f.png)

**Comment by beckernick** [comment] 2023-01-12 14:31
Cross-linking a comment in a cuML issue, which is relevant to this discussion.

        I see you're using `calculate_probabilities=True`. The difference is likely that in BERTopic v0.13 the HDBSCAN soft probabilities are being calculated with cuML's HDBSCAN, where is in BERTopic v0.12 they were being calculated using the CPU HDBSCAN. This is a good thing in general, as calculating the soft probabilities on 2 million documents with CPU HDBSCAN would likely be *very* slow (see [this blog for some loose benchmarks in which it took 15+ hours on a CPU to do 400K documents vs. 1-2 seconds on a GPU](https://developer.nvidia.com/blog/faster-hdbscan-soft-clustering-with-rapids-cuml/), though results will vary across CPU and GPU types).

        Computing the soft probabilities with cuML's HDBSCAN can have significant memory requirements if the number of clusters is very large. We have an [open issue to address this](https://github.com/rapidsai/cuml/issues/4879), and there are some recommendations for how to work around the memory issues in the meantime by changing the HDBSCAN configuration in the issue. If you prefer to use a very small minimum cluster size, you may need to use the CPU version for now (but you can still use cuML's UMAP).

        I'm going to cross-link https://github.com/MaartenGr/BERTopic/issues/922 and recommend we take further discussion to that issue. Since this issue is now a duplicate of #4879 from a cuML perspective, I'm going to close it. But please feel free to continue the discussion in the BERTopic issue or in #4879

_Originally posted by @beckernick in https://github.com/rapidsai/cuml/issues/5127#issuecomment-1380440159_

**Comment by Thiziri-Hafir** [comment] 2023-01-13 10:51
Thanks for the answer, I will look into it but in the meantime I have a new error with UMAP : 
`RuntimeError: CUDA error encountered at: file=/opt/conda/envs/rapids-22.12/include/raft/core/handle.hpp line=301: `

**Comment by constantin-barbu** [comment] 2023-01-26 21:15
I'm getting the error when processing a 220k document dataset that I was able to process before (on BERTopic 0.12) without issue. I can still process other much larger datasets, 1M+, of the same kind with no issue :|. Reducing the n_neighbors parameter for UMAP from 15 to 10 seems to work, but it's strange, since it worked fine before / still works on other data.

**Comment by Thiziri-Hafir** [comment] 2023-02-06 15:22
I've tried  increasing both `min_samples` and `min_cluster_size' as mentioned above but still doesn't work for me.

**Comment by MaartenGr** [comment] 2023-05-23 09:54
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!

**Closed by MaartenGr** 2023-05-23 09:54 UTC
