### ISSUE TITLE
BrokenProcessPool 

### ISSUE THREAD

**Issue by Kaleemullahqasim** [MaartenGr/BERTopic#338] opened 2021-11-22 05:46 UTC
Bertopic is sending a BrokenProcessPool while building the topics. 
A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
Was working smooth before but suddenly started sending this error.

` def __get_result(self):
        if self._exception:
            raise self._exception
        else:
            return self._result
`

**Comment by MaartenGr** [comment] 2021-11-22 08:52
Could you try running BERTopic from a fresh environment? Perhaps some things have changed in the environment you are currently working that could have influenced some things in BERTopic. Also, could you share the code you are using, the full error output, and the BERTopic version you are using?

**Comment by Kaleemullahqasim** [comment] 2021-11-23 04:49
### This is the error
`hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__()

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds()
/usr/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result
BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.`

### Versions 
bertopic==0.9.3
hdbscan==0.8.27

### Code i am running 
`data = df['clean_reviews']
Word = list(set(words.words()))
df_final = df[df['clean_reviews'].str.contains('|'.join(Word))]
docs_test = list(df_final.loc[:, 'clean_reviews'].values)
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs_test)`

**Comment by Kaleemullahqasim** [comment] 2021-11-23 04:49
Yes and i have also factory reset the google colab evn

**Comment by MaartenGr** [comment] 2021-11-23 06:07
Ah, then it might be the case that you have a very large dataset (> 500.000 records). If that is the case, then installing HDBSCAN from the master branch might solve your issue. There was an issue a while ago that was fixed with a commit in the master branch. Installing that might fix your issue.

**Comment by Kaleemullahqasim** [comment] 2021-11-23 06:15
actully i tried to reduce the dataset size with 
`docs_test = docs_test[:7000]` 
just to check if that is issue with number of rows present in dataset.
but it still gave the same error, mean limiting the dataset didnt work for me.

**Comment by MaartenGr** [comment] 2021-11-23 10:02
Strange, if you are running your code on Google Colab, is the data you are using publicly available? If yes, can you create a reproducible example so that I can test some things out?

**Comment by Kaleemullahqasim** [comment] 2021-11-24 07:02
It is working now Maarten with your last commit branch. Thanks a lot.

**Comment by Kaleemullahqasim** [comment] 2021-11-24 07:03
yeah now if i limit the dataset it do work but without 
`docs_test = docs_test[:7000]`
it still shoot same error. 
I have tried the master branch of your last commit

**Comment by MaartenGr** [comment] 2021-11-24 07:10
Have you tried the master branch of HDBSCAN and not that of BERTopic? The `BrokenProcessPool` stems from HDBSCAN so that means that you will first need to install BERTopic and then update HDBSCAN with the master branch:

```bash
pip install bertopic
pip uninstall hdbscan
pip install --upgrade git+https://github.com/scikit-learn-contrib/hdbscan@master#egg=hdbscan
```

**Comment by Kaleemullahqasim** [comment] 2021-11-24 16:39
Yeap it is working now. thanks a lot Maarten. Please let me know if i can have your personal email.

**Comment by MaartenGr** [comment] 2021-11-25 12:40
If you have any questions, you can contact me on [LinkedIn](https://www.linkedin.com/in/mgrootendorst/) as I am typically more active there than my email. Feel free to ask any questions and I'll make sure not to wait too long to answer them!

**Comment by Kaleemullahqasim** [comment] 2021-11-29 04:58
Maarten i did send you a text on LinkedIn.

**Comment by MaartenGr** [comment] 2021-12-08 12:43
Since the discussion continued on LinkedIn, I will be closing this issue.

**Closed by MaartenGr** 2021-12-08 12:43 UTC
