### ISSUE TITLE
Paralellizing bert topic

### ISSUE THREAD

**Issue by RahulDasari** [MaartenGr/BERTopic#174] opened 2021-07-07 08:50 UTC
I'm having issues running bert topic in a parallel processing fashion. I've pasted the code snippet below- I'm attempting to run a parameter gird on bertopic. 

run_hyperparameter_grid is a function that fits bertopic on a set of docs.
print("topic model running" + str(topic_model))  
prints topic model running<bertopic._bertopic.BERTopic object at 0x7f7d62a4f150>

https://github.com/RahulDasari/bertopic_problem/blob/e776e694a7bf83493c23d899b18192ed57c001ae/problem_snippet

**Comment by MaartenGr** [comment] 2021-07-07 09:36
Could you format the codeblock in these ``` brackets with the corresponding indentation? Seeing as you have multiple for loops it is difficult to read the code as it is now. 

Also, I might be mistaken but I do not see any error message. What issue are you exactly encountering?

**Comment by RahulDasari** [comment] 2021-07-07 11:15
So, there is no error message, it just keeps running indefinitely without executing topic_model.fit_transform(docs)
please find the code snippet on the link below:
https://github.com/RahulDasari/bertopic_problem/blob/e776e694a7bf83493c23d899b18192ed57c001ae/problem_snippet

**Comment by MaartenGr** [comment] 2021-07-07 14:47
Based on the snippet it is difficult to tell where the issue is. However, parallelizing a GPU-based model is typically quite difficult and might present with a number of issues. I am quite sure you simply cannot parallelize the model like that as long as you use the GPU.

**Comment by MaartenGr** [comment] 2021-07-19 10:37
Since there hasn't been a response, I am closing this for now. If you still have any issues, feel free to re-open the issue and we'll take another look at!

**Closed by MaartenGr** 2021-07-19 10:37 UTC
