### ISSUE TITLE
Incorrect tooltip when hovering

### ISSUE THREAD

**Issue by mrmutator** [MaartenGr/BERTopic#1237] opened 2023-05-07 11:41 UTC
BERTopic 0.14.1

Hi, I've been playing around with BERTopic and I realized that the tooltips in the hierarchical clustering visualization are a bit off in some cases. It seems that the merged topic representations are shown at the wrong merge node.

![image](https://user-images.githubusercontent.com/7478859/236675316-9bdac825-d62a-403f-8767-49df8e4220d1.png)

**Comment by MaartenGr** [comment] 2023-05-07 13:03
Thank you for sharing! This is a known issue and is fixed in the main branch of BERTopic. There is an upcoming release that will introduce a number of new features as well as a fix for this issue. If you want to resolve it now, I would advise installing BERTopic from its latest commit.

**Comment by mommi84** [comment] 2023-05-25 17:48
The latest commit fixes the sorting problem, however I noticed that the parent name ignores the `Parent_Name` column and some other name is displayed instead. In this example, the hovered hierarchical topic `892` should be displayed as `nuclear_nuclear weapons_weapons_treaty_russian`.

<img width="883" alt="Screenshot 2023-05-25 at 19 40 52" src="https://github.com/MaartenGr/BERTopic/assets/91099/3d9c51b9-e19d-4d28-a4cc-4d599946a147">

**Comment by MaartenGr** [comment] 2023-05-25 17:53
@mommi84 Hmmm, not quite sure what is happening there. Do you by chance have a reproducible example?

**Comment by mommi84** [comment] 2023-05-26 09:17
I think I know what happened. I had saved the hierarchical topics dataframe into a CSV file. In the original dataframe, topic IDs are strings, whereas when the dataframe is loaded into `df_h` from CSV they are automatically cast to ints. All good now.

**Comment by MaartenGr** [comment] 2023-05-28 04:48
Great! Glad to hear that you solved the issue. If you run into any other issues, please let me know.

**Comment by stepwei** [comment] 2023-07-12 13:38
Hi Maarten, has this issue been resolved in your latest Bertopic version (tooltip error)?  I still seem to have this issue in version 0.15.0.

e.g. 
-wegen_aantal_weg_wet_stelling
│    │    │         │    │    │              │    │    │    │    ├─■──trans_trans personen_transgenders_transgenderzorg_excuses ── 
│    │    │         │    │    │              │    │    │    │    └─■──achternaam_achternaamwijziging_voornaam ── 

This is part of the tree I obtained while using `get_topic_tree`. Moreover, I see the same happening in visualize_hierarchy.
I would not expect this parent topic with these childtopics.

**Comment by MaartenGr** [comment] 2023-07-12 19:54
It should indeed be solved since the `get_topic_tree` was never part of the problem. That means that in your instance it shows how topics could be combined if they would be forced to combine. In other words, depending on how you performed your hierarchical topic modeling, what you are seeing is the model deciding that this is the only possible way to combine the topics even though it is a poor one. It chooses the best possible solution out of a bunch of poor ones. 

Perhaps to make it, even more, clearer, the goal of hierarchical topic modeling is to combine topics until a single topic remains. That single topic would then be the culmination of all documents and would be essentially meaningless. However, to get to that point you would need to combine all topics, even though they might not make sense. This is not necessarily a bad thing as it allows the user to decide a threshold for combining topics. This threshold can also be found int he dataframe returned when performing hierarchical topic modeling. It allows you to decide to which level of abstraction you would like to go. 

I believe you could account for this by specifying `max_distance` in `get_topic_tree`. This parameter makes it so that topics that are far apart should not be visualized in this tree as that might be misleading. It essentially allows you to set a threshold for when topics should be merged.

**Comment by stepwei** [comment] 2023-07-13 11:29
Hi Maarten,

Alright, I expected for instance as in the example below that the parent topic (here auto_aantal_uur_aanpak_belgië) would be closer to its child topics. Now, that would be a cool feature :) !
For this particular example (which contains open data, no worries) the parent topic has nothing to do with the two child topics. Hence my question.

![snippet](https://github.com/MaartenGr/BERTopic/assets/84676607/d75fa052-13ce-47d9-a378-3265cf8af435)

**Comment by MaartenGr** [comment] 2023-07-13 11:38
In that case, could you share your full code? It would be easier to see what is happening with a bit more context. Just to be sure, you did the entire training in v0.15, right? You did not load the model in from a saved checkpoint?

**Comment by MaartenGr** [comment] 2023-09-27 09:06
Closing this due to inactivity. Let me know if I need to re-open the issue!

**Closed by MaartenGr** 2023-09-27 09:06 UTC
