### ISSUE TITLE
Question regarding assign topics to new dataset using pretrained model

### ISSUE THREAD

**Issue by cckimm** [MaartenGr/BERTopic#467] opened 2022-03-06 06:21 UTC
Hello, 
I have one question about assigning topics to new set of documents using a pretrained Bertopic Model.

In my situation, I already have 519 topics generated by pretrained Bertopic Model. I have additional 10,000 documents that I would like to assign to pre-existing 519 topics from pretrained model. Is this task possible to perform using transform? If so, could you help me understand the process?

I emphasize that additional 10,000 documents should be assigned to previously generated 519 topics.

**Comment by MaartenGr** [comment] 2022-03-07 07:20
After fitting a BERTopic model, you can use that same model to assign unseen documents to the previously generated topics. To do this, you can simply use `topics, probs = my_pretrained_model.transform(unseen_docs)`. 

The `.transform()` steps work very similar to the `fit()` step as defined [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html). Essentially, at each step, we use the fitted models (UMAP, HDBSCAN, cTFIDF, etc.) to perform the predictions for the new documents.

**Comment by vsean103** [comment] 2022-04-02 01:03
Hi Maarten! The following is my code that I used for building BERTopic model. I found out that the predicted topics on unseen docs are not consistent. For example, if topic #2 in the variable "topics" is related to "Cat", topic #2 in "topics_unseen" is not related to Cat. Can you advise how to solve this problem?

```
random_state = 12345
umap_model = UMAP(random_state=random_state)

topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True, embedding_model="all-mpnet-base-v2", diversity=0.8, top_n_words=20, nr_topics=20, n_gram_range=(2,3),umap_model=umap_model)

topics, probs = topic_model.fit_transform(docs)

topics_unseen, probs_unseen = topic_model.transform(unseen_docs)
```

**Comment by MaartenGr** [comment] 2022-04-02 06:44
@vsean103 Based on your code, am I correct in stating that the documents in `docs` are different from those in `unseen_docs`? In that case, it would make sense that the resulting topics are different since you are predicting the topics for different topics.

**Comment by vsean103** [comment] 2022-04-04 21:01
@MaartenGr Thanks for your response. Yes, "docs" and "unseen_docs" are different. I used "docs" to train the model to find 20 topics and want to predict topics for "unseen_docs" using this previously trained model. The "unseen_docs" should contain more or less the same topics as in "docs" (they have the same topic space).

I understand that the prediction is different for the "unseen_docs" but the topic # assignment is not consistent. For example, when we look at top_n_words for topic #2, we see that the topic is about Cat, and topic #3 is about Dog. But, when we predicted "unseen_docs" and looked at top_n_words for each assigned topic, we see topic #10 is related to Cat, and topic #5 is the Dog.

Could you please advise?

**Comment by MaartenGr** [comment] 2022-04-05 13:10
@vsean103 I am not entirely sure if I understand you correctly. The topics themselves should not change when you transform on `unseen_docs`. Could you create a reproducible example for me to try out?

**Comment by cb-pratibhasaha** [comment] 2022-04-13 08:57
What if I want to see the topics each document has been assigned to? How to go about that? I have a dataframe and used a column of text to train a Bertopic model over them. How do I see which topic each row of the dataframe has been assigned to?

**Comment by MaartenGr** [comment] 2022-04-13 11:12
@cb-pratibhasaha When you fit and transform a BERTopic instance, you get the `topics` variable as a result. That is a list of topics where each element corresponds to the topic in `docs`. In other words, the topic for `docs[0]` is `topics[0]`, for `docs[1]` it is `topics[1]`, etc. This means that you can do the following to add the topics: `df["Topics"] = topics`.

**Comment by cb-pratibhasaha** [comment] 2022-04-19 09:17
Thanks for the help! I need to ask what does topic -1 signify? There are rows under topic -1 which could have been classified into the other clusters...Why is that happening and how do I reduce these outliers without compromising these clusters. Do give me insight on the same. Thanks!

**Comment by MaartenGr** [comment] 2022-04-19 12:27
All documents in topic -1 are outliers. Those are documents that could not be confidently classified as being in certain clusters and are hence classified as outliers. You can reduce, as mentioned in the documentation [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers) but there is a risk of adding noise to clusters when doing so.

**Closed** 2022-05-01 19:42 UTC
