### ISSUE TITLE
Different topic inference if repeat the transform function on the same document

### ISSUE THREAD

**Issue by paulthemagno** [MaartenGr/BERTopic#426] opened 2022-01-31 12:19 UTC
I'm doing some tests with a model using the `paraphrase-multilingual-mpnet-base-v2`.
I'd like to get the topic of an **unseen document** (so I didn't insert it when I did the clustering).

It seems that using the **same document**, the model **sometimes infers a topic, sometimes another one**. I don't know if this is an expected behavior. My intuition is that the same document should be tagged in the same way always.

To do this test I printed the output 20 times with the same string, and 18/20 times the topic was 19 and 2/20 an outlier (-1).

```python
for i in range (0,20):
    print(my_model.transform("""TEXT""")[0])
```

the output was:
```
Batches: 100%
1/1 [00:00<00:00, 6.47it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 7.28it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 5.73it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 3.94it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 3.93it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 7.52it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 5.64it/s]
[-1]
Batches: 100%
1/1 [00:00<00:00, 4.49it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 6.60it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 8.01it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 7.28it/s]
[-1]
Batches: 100%
1/1 [00:00<00:00, 4.22it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 4.13it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 5.59it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 3.78it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 4.59it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 5.97it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 4.20it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 5.52it/s]
[19]
Batches: 100%
1/1 [00:00<00:00, 4.28it/s]
[19]
```

**Comment by MaartenGr** [comment] 2022-02-01 07:30
The stochastic nature of UMAP can result in unstable predictions, to prevent this from happening you can set a `random_state` in UMAP at the expense of performance. You can find a bit more about that [here](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs).

If, for whatever reason, you cannot set a `random_state`, then you could also take the `np.argmax` of the resulting probability matrix. It will force every prediction to be assigned to a non-outlier topic.

**Comment by paulthemagno** [comment] 2022-02-01 08:58
That's very useful, thanks! 
I thought the randomicity was in the step of `fit`, so while I'm creating the model, and not when I do a `transform`.
I mean I thought that once the model is created, if I want to do only inferences, it would have been a cosine distance between the embedding of the document and the embeddings of the centroids of the topics, but I was probably wrong.

So the solution is something like that:
```python
umap_model = UMAP(n_neighbors=15, n_components=5, 
                  min_dist=0.0, metric='cosine', random_state=42)
topic_model = BERTopic(umap_model=umap_model)
```

**Comment by MaartenGr** [comment] 2022-02-01 10:24
The `transform` stage runs through similar steps as the `fit` stage. However, instead of fitting each sub-model (UMAP, HDBSCAN, c-TF-IDF), it now uses those models for prediction only. The difficulty with taking the cosine distance between the embedding of the document and the embeddings of the centroids is that you assume that the centroid is the best representation of a cluster. In practice, especially with a density-based technique such as HDBSCAN, this is not always the case. 

Take, for example, a cluster in the form of the outer line of a circle. The centroid of that cluster would be at the center of the circle, but since all points lie on the outer line of the circle it is not very representative of the cluster. 

> So the solution is something like that:

Yep! This allows you to create more stable results but does come at the cost of [performance](https://umap-learn.readthedocs.io/en/latest/reproducibility.html).

**Closed** 2022-03-20 07:09 UTC
