### ISSUE TITLE
Feature Request: Add logging to transform()

### ISSUE THREAD

**Issue by Rysias** [MaartenGr/BERTopic#356] opened 2021-12-06 12:54 UTC
When dealing with large datasets (1M+ rows), transform can take quite a long time. Therefore, it would be lovely, if there were some logging of the progress (i.e. when is it using UMAP versus HDBSCAN), like there is in the fit_transform()-function. I would be more than happy to submit a PR but it shouldn't take too much time to do :)) 

Thank you yet again for your magnificent work!

**Comment by MaartenGr** [comment] 2021-12-06 14:15
Sure! 😄 

I added some basic logging to the `.transform()` function in the pull request for version v0.9.4 (#335). Is that what you had in mind?

**Comment by Rysias** [comment] 2021-12-06 16:21
That is absolutely perfect, thank you!

**Comment by MaartenGr** [comment] 2021-12-16 07:24
This was added to the v0.9.4 release of BERTopic so I'll be closing this. Let me know if it does not work out as intended!

**Closed by MaartenGr** 2021-12-16 07:24 UTC

**Comment by yotammarton** [comment] 2021-12-22 10:19
> 
That's exactly what I needed, Thanks!
Although using v0.9.4 I had to change the following from `WARNING` to `DEBUG` in order to see the printed logs (assuming `INFO` would also work).
https://github.com/MaartenGr/BERTopic/blob/cd98fc8d22ab1eba593c518278ce479d2879c372/bertopic/_bertopic.py#L37

Is there a way to set the logger level from outside?

*Might be good to mention that my model is trained on v0.9.2 and I do inference on v0.9.4 for this feature

**Comment by MaartenGr** [comment] 2021-12-23 11:40
You can only update the logger when instantiating BERTopic through `verbose=True`. You might have set it to False when you saved the model. It would be nice though if we could update it after creating the model. I will add it to the list!

**Comment by yotammarton** [comment] 2021-12-26 08:56
Thanks Maarten.
Actually I have set up BERTopic with `verbose=True` during training, saved the model using `save`, and loaded using `load`.
(might it be something related to the face i'm manually passing `embedding_model` to BERTopic?)

Glad it will be added in the future 👏
